using Pecus.Libs.DB.Models.Enums;

namespace Pecus.Libs.DB.Models;

/// <summary>
/// ログインユーザーエンティティ
/// </summary>
public class User
{
    /// <summary>
    /// ユーザーID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// ログインID(システム内でユニークなハッシュ文字列)
    /// </summary>
    public required string LoginId { get; set; }

    /// <summary>
    /// ユーザー名
    /// </summary>
    public required string Username { get; set; }

    /// <summary>
    /// メールアドレス
    /// </summary>
    public required string Email { get; set; }

    /// <summary>
    /// パスワードハッシュ
    /// </summary>
    public required string PasswordHash { get; set; }

    /// <summary>
    /// アイデンティティアイコンタイプ(Gravatar, UserAvatar, AutoGenerated)
    /// </summary>
    public AvatarType? AvatarType { get; set; }

    /// <summary>
    /// ユーザーがアップロードしたカスタムアバター画像のパス（ファイル名）
    /// AvatarTypeがUserAvatarの場合、アップロードされたファイルのパス（例："/api/downloads/avatar/3/abc123.png" または "abc123.png"）を保持
    /// 他のAvatarTypeに変更しても、このパスは保持され続けるため、再度UserAvatarに戻した際に再利用可能
    /// </summary>
    public string? UserAvatarPath { get; set; }

    /// <summary>
    /// 組織ID
    /// </summary>
    public int? OrganizationId { get; set; }

    /// <summary>
    /// 所属組織
    /// </summary>
    public Organization? Organization { get; set; }

    /// <summary>
    /// 作成日時
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// 作成者ユーザーID
    /// </summary>
    public int? CreatedByUserId { get; set; }

    /// <summary>
    /// 最終ログイン日時
    /// </summary>
    public DateTimeOffset? LastLoginAt { get; set; }

    /// <summary>
    /// 更新日時
    /// </summary>
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>
    /// 更新者ユーザーID
    /// </summary>
    public int? UpdatedByUserId { get; set; }

    /// <summary>
    /// パスワード設定トークン（新規ユーザー登録時のパスワード設定用）
    /// </summary>
    public string? PasswordResetToken { get; set; }

    /// <summary>
    /// パスワード設定トークンの有効期限
    /// </summary>
    public DateTimeOffset? PasswordResetTokenExpiresAt { get; set; }

    /// <summary>
    /// アクティブフラグ
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// このユーザーに割り当てられたロール
    /// </summary>
    public ICollection<Role> Roles { get; set; } = new List<Role>();

    /// <summary>
    /// このユーザーが参加しているワークスペース
    /// </summary>
    public ICollection<WorkspaceUser> WorkspaceUsers { get; set; } = new List<WorkspaceUser>();

    /// <summary>
    /// このユーザーがPINしているワークスペースアイテム
    /// </summary>
    public ICollection<WorkspaceItemPin> WorkspaceItemPins { get; set; } =
        new List<WorkspaceItemPin>();

    /// <summary>
    /// このユーザーが持つスキル
    /// </summary>
    public ICollection<UserSkill> UserSkills { get; set; } = new List<UserSkill>();

    /// <summary>
    /// ユーザー設定
    /// </summary>
    public UserSetting? Setting { get; set; }

    /// <summary>
    /// このユーザーに紐づく端末（デバイス）
    /// </summary>
    public List<Device> Devices { get; set; } = new();

    /// <summary>
    /// チャットアクター（ナビゲーションプロパティ）
    /// ユーザー作成時に自動生成される
    /// </summary>
    public ChatActor? ChatActor { get; set; }

    /// <summary>
    /// 楽観的ロック用バージョン番号（PostgreSQL の xmin システムカラム）
    /// </summary>
    public uint RowVersion { get; set; }
}