using Pecus.Libs.DB.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace Pecus.Models.Responses.User;

/// <summary>
/// ユーザー詳細レスポンス
/// </summary>
public class UserDetailResponse : IConflictModel
{
    /// <summary>
    /// ユーザーID
    /// </summary>
    [Required]
    public required int Id { get; set; }

    /// <summary>
    /// 組織ID
    /// </summary>
    public int? OrganizationId { get; set; }

    /// <summary>
    /// ログインID
    /// </summary>
    [Required]
    public required string LoginId { get; set; }

    /// <summary>
    /// ユーザー名
    /// </summary>
    [Required]
    public required string Username { get; set; }

    /// <summary>
    /// メールアドレス
    /// </summary>
    [Required]
    public required string Email { get; set; }

    /// <summary>
    /// アバタータイプ
    /// </summary>
    public AvatarType? AvatarType { get; set; }

    /// <summary>
    /// ユーザーがアップロードしたカスタムアバター画像のパス（ファイル名）
    /// AvatarTypeに関わらず、過去にアップロードされたファイルのパスを保持（再利用可能）
    /// </summary>
    public string? UserAvatarPath { get; set; }

    /// <summary>
    /// アイデンティティアイコンURL（表示用）
    /// AvatarTypeに応じて適切なURL（Gravatar/UserAvatar/AutoGenerated）が設定される
    /// 必ず有効なURLが返されるため、クライアント側でnullチェック不要
    /// </summary>
    [Required]
    public required string IdentityIconUrl { get; set; }

    /// <summary>
    /// ユーザーのロール一覧
    /// </summary>
    [Required]
    public required List<UserRoleResponse> Roles { get; set; } = new();

    /// <summary>
    /// ユーザーのスキル一覧
    /// </summary>
    public List<UserSkillResponse> Skills { get; set; } = new();

    /// <summary>
    /// 管理者権限を持つかどうか
    /// </summary>
    [Required]
    public required bool IsAdmin { get; set; }

    /// <summary>
    /// アクティブなユーザーかどうか
    /// </summary>
    public bool IsActive { get; set; }

    /// <summary>
    /// 作成日時
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// 最終ログイン日時
    /// </summary>
    public DateTimeOffset? LastLoginAt { get; set; }

    /// <summary>
    /// ユーザーの楽観的ロック用RowVersion
    /// </summary>
    [Required]
    public required uint RowVersion { get; set; }

    /// <summary>
    /// ユーザー設定（プロフィール設定画面でのみ返却）
    /// </summary>
    public UserSettingResponse? Setting { get; set; }
}