/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActivityActionType } from './models/ActivityActionType';
export type { ActivityPeriod } from './models/ActivityPeriod';
export type { ActivityResponse } from './models/ActivityResponse';
export type { ActivityResponsePagedResponse } from './models/ActivityResponsePagedResponse';
export type { AddUserToWorkspaceRequest } from './models/AddUserToWorkspaceRequest';
export type { AddWorkspaceItemRelationRequest } from './models/AddWorkspaceItemRelationRequest';
export type { AddWorkspaceItemRelationResponse } from './models/AddWorkspaceItemRelationResponse';
export type { AdminUpdateOrganizationRequest } from './models/AdminUpdateOrganizationRequest';
export type { AdminUpdateOrganizationSettingRequest } from './models/AdminUpdateOrganizationSettingRequest';
export type { AssigneeTaskLoadResponse } from './models/AssigneeTaskLoadResponse';
export type { AvatarType } from './models/AvatarType';
export type { CreateOrganizationRequest } from './models/CreateOrganizationRequest';
export type { CreateSkillRequest } from './models/CreateSkillRequest';
export type { CreateTagRequest } from './models/CreateTagRequest';
export type { CreateTaskCommentRequest } from './models/CreateTaskCommentRequest';
export type { CreateUserWithoutPasswordRequest } from './models/CreateUserWithoutPasswordRequest';
export type { CreateWorkspaceItemRequest } from './models/CreateWorkspaceItemRequest';
export type { CreateWorkspaceRequest } from './models/CreateWorkspaceRequest';
export type { CreateWorkspaceTaskRequest } from './models/CreateWorkspaceTaskRequest';
export type { DashboardHotItemsResponse } from './models/DashboardHotItemsResponse';
export type { DashboardHotWorkspacesResponse } from './models/DashboardHotWorkspacesResponse';
export type { DashboardItemSummary } from './models/DashboardItemSummary';
export type { DashboardPersonalSummaryResponse } from './models/DashboardPersonalSummaryResponse';
export type { DashboardSummaryResponse } from './models/DashboardSummaryResponse';
export type { DashboardTaskFilter } from './models/DashboardTaskFilter';
export type { DashboardTasksByPriorityResponse } from './models/DashboardTasksByPriorityResponse';
export type { DashboardTaskSummary } from './models/DashboardTaskSummary';
export type { DashboardTaskTrendResponse } from './models/DashboardTaskTrendResponse';
export type { DashboardWorkspaceBreakdownResponse } from './models/DashboardWorkspaceBreakdownResponse';
export type { DashboardWorkspaceStatistics } from './models/DashboardWorkspaceStatistics';
export type { DeleteTaskCommentRequest } from './models/DeleteTaskCommentRequest';
export type { DeviceResponse } from './models/DeviceResponse';
export type { DeviceType } from './models/DeviceType';
export type { EmailChangeRequestResponse } from './models/EmailChangeRequestResponse';
export type { EmailChangeVerifyResponse } from './models/EmailChangeVerifyResponse';
export type { ErrorResponse } from './models/ErrorResponse';
export type { FileType } from './models/FileType';
export type { FileUploadResponse } from './models/FileUploadResponse';
export type { FocusRecommendationResponse } from './models/FocusRecommendationResponse';
export type { FocusTaskResponse } from './models/FocusTaskResponse';
export type { GenerativeApiVendor } from './models/GenerativeApiVendor';
export type { GenreCount } from './models/GenreCount';
export type { HelpNotificationTarget } from './models/HelpNotificationTarget';
export type { HotItemEntry } from './models/HotItemEntry';
export type { HotWorkspaceEntry } from './models/HotWorkspaceEntry';
export type { ItemWithTasksResponse } from './models/ItemWithTasksResponse';
export type { ItemWithTasksResponsePagedResponse } from './models/ItemWithTasksResponsePagedResponse';
export type { LandingPage } from './models/LandingPage';
export type { LoginDeviceInfo } from './models/LoginDeviceInfo';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { MasterGenreResponse } from './models/MasterGenreResponse';
export type { MasterSkillResponse } from './models/MasterSkillResponse';
export type { MasterTaskTypeResponse } from './models/MasterTaskTypeResponse';
export type { MessageResponse } from './models/MessageResponse';
export type { MyCommitterWorkspaceResponse } from './models/MyCommitterWorkspaceResponse';
export type { MyItemRelationType } from './models/MyItemRelationType';
export type { MyTaskDetailResponse } from './models/MyTaskDetailResponse';
export type { MyTaskDetailResponseWorkspaceTaskStatisticsPagedResponse } from './models/MyTaskDetailResponseWorkspaceTaskStatisticsPagedResponse';
export type { MyTaskWorkspaceResponse } from './models/MyTaskWorkspaceResponse';
export type { OrganizationInfoResponse } from './models/OrganizationInfoResponse';
export type { OrganizationPlan } from './models/OrganizationPlan';
export type { OrganizationResponse } from './models/OrganizationResponse';
export type { OrganizationResponseConcurrencyErrorResponse } from './models/OrganizationResponseConcurrencyErrorResponse';
export type { OrganizationSettingResponse } from './models/OrganizationSettingResponse';
export type { OrganizationSettingResponseConcurrencyErrorResponse } from './models/OrganizationSettingResponseConcurrencyErrorResponse';
export type { OrganizationWithAdminResponse } from './models/OrganizationWithAdminResponse';
export type { OSPlatform } from './models/OSPlatform';
export type { PendingEmailChangeResponse } from './models/PendingEmailChangeResponse';
export type { PredecessorTaskInfo } from './models/PredecessorTaskInfo';
export type { PriorityTaskCount } from './models/PriorityTaskCount';
export type { ProblemDetails } from './models/ProblemDetails';
export type { RecipientRequest } from './models/RecipientRequest';
export type { RefreshRequest } from './models/RefreshRequest';
export type { RefreshResponse } from './models/RefreshResponse';
export type { RelatedItemInfo } from './models/RelatedItemInfo';
export type { RelationType } from './models/RelationType';
export type { RequestEmailChangeRequest } from './models/RequestEmailChangeRequest';
export type { RequestPasswordResetRequest } from './models/RequestPasswordResetRequest';
export type { ResetPasswordRequest } from './models/ResetPasswordRequest';
export type { RoleInfoResponse } from './models/RoleInfoResponse';
export type { RoleListItemResponse } from './models/RoleListItemResponse';
export type { RoleResponse } from './models/RoleResponse';
export type { RoleUserCountResponse } from './models/RoleUserCountResponse';
export type { SetOwnSkillsRequest } from './models/SetOwnSkillsRequest';
export type { SetTagsToItemRequest } from './models/SetTagsToItemRequest';
export type { SetUserActiveStatusRequest } from './models/SetUserActiveStatusRequest';
export type { SetUserPasswordRequest } from './models/SetUserPasswordRequest';
export type { SetUserRolesRequest } from './models/SetUserRolesRequest';
export type { SetUserSkillsRequest } from './models/SetUserSkillsRequest';
export type { SetWorkspaceSkillsRequest } from './models/SetWorkspaceSkillsRequest';
export type { SkillDetailResponse } from './models/SkillDetailResponse';
export type { SkillDetailResponseConcurrencyErrorResponse } from './models/SkillDetailResponseConcurrencyErrorResponse';
export type { SkillListItemResponse } from './models/SkillListItemResponse';
export type { SkillListItemResponseSkillStatisticsPagedResponse } from './models/SkillListItemResponseSkillStatisticsPagedResponse';
export type { SkillResponse } from './models/SkillResponse';
export type { SkillStatistics } from './models/SkillStatistics';
export type { SkillUsageItem } from './models/SkillUsageItem';
export type { SkillUserCountResponse } from './models/SkillUserCountResponse';
export type { SuccessResponse } from './models/SuccessResponse';
export type { TagDetailResponse } from './models/TagDetailResponse';
export type { TagDetailResponseConcurrencyErrorResponse } from './models/TagDetailResponseConcurrencyErrorResponse';
export type { TagInfoResponse } from './models/TagInfoResponse';
export type { TagListItemResponse } from './models/TagListItemResponse';
export type { TagListItemResponseTagStatisticsPagedResponse } from './models/TagListItemResponseTagStatisticsPagedResponse';
export type { TagResponse } from './models/TagResponse';
export type { TagStatistics } from './models/TagStatistics';
export type { TagUsageItem } from './models/TagUsageItem';
export type { TaskCommentDetailResponse } from './models/TaskCommentDetailResponse';
export type { TaskCommentDetailResponseConcurrencyErrorResponse } from './models/TaskCommentDetailResponseConcurrencyErrorResponse';
export type { TaskCommentDetailResponsePagedResponse } from './models/TaskCommentDetailResponsePagedResponse';
export type { TaskCommentResponse } from './models/TaskCommentResponse';
export type { TaskCommentType } from './models/TaskCommentType';
export type { TaskItemResponse } from './models/TaskItemResponse';
export type { TaskPriority } from './models/TaskPriority';
export type { TasksByDueDateResponse } from './models/TasksByDueDateResponse';
export type { TaskScoreDetail } from './models/TaskScoreDetail';
export type { TaskStatusFilter } from './models/TaskStatusFilter';
export type { TaskWithItemResponse } from './models/TaskWithItemResponse';
export type { TempAttachmentResponse } from './models/TempAttachmentResponse';
export type { UpdatePasswordRequest } from './models/UpdatePasswordRequest';
export type { UpdateProfileRequest } from './models/UpdateProfileRequest';
export type { UpdateSkillRequest } from './models/UpdateSkillRequest';
export type { UpdateTagRequest } from './models/UpdateTagRequest';
export type { UpdateTaskCommentRequest } from './models/UpdateTaskCommentRequest';
export type { UpdateUserSettingRequest } from './models/UpdateUserSettingRequest';
export type { UpdateWorkspaceItemAssigneeRequest } from './models/UpdateWorkspaceItemAssigneeRequest';
export type { UpdateWorkspaceItemAttributeRequest } from './models/UpdateWorkspaceItemAttributeRequest';
export type { UpdateWorkspaceItemRequest } from './models/UpdateWorkspaceItemRequest';
export type { UpdateWorkspaceItemStatusRequest } from './models/UpdateWorkspaceItemStatusRequest';
export type { UpdateWorkspaceRequest } from './models/UpdateWorkspaceRequest';
export type { UpdateWorkspaceTaskRequest } from './models/UpdateWorkspaceTaskRequest';
export type { UpdateWorkspaceUserRoleRequest } from './models/UpdateWorkspaceUserRoleRequest';
export type { UserDetailResponse } from './models/UserDetailResponse';
export type { UserDetailResponseConcurrencyErrorResponse } from './models/UserDetailResponseConcurrencyErrorResponse';
export type { UserDetailResponseUserStatisticsPagedResponse } from './models/UserDetailResponseUserStatisticsPagedResponse';
export type { UserRoleResponse } from './models/UserRoleResponse';
export type { UserSearchResultResponse } from './models/UserSearchResultResponse';
export type { UserSearchSkillResponse } from './models/UserSearchSkillResponse';
export type { UserSettingResponse } from './models/UserSettingResponse';
export type { UserSettingResponseConcurrencyErrorResponse } from './models/UserSettingResponseConcurrencyErrorResponse';
export type { UserSkillResponse } from './models/UserSkillResponse';
export type { UserStatistics } from './models/UserStatistics';
export type { WeeklyTaskTrend } from './models/WeeklyTaskTrend';
export type { WorkspaceDetailResponse } from './models/WorkspaceDetailResponse';
export type { WorkspaceDetailResponseConcurrencyErrorResponse } from './models/WorkspaceDetailResponseConcurrencyErrorResponse';
export type { WorkspaceDetailUserResponse } from './models/WorkspaceDetailUserResponse';
export type { WorkspaceFullDetailResponse } from './models/WorkspaceFullDetailResponse';
export type { WorkspaceItemAttachmentResponse } from './models/WorkspaceItemAttachmentResponse';
export type { WorkspaceItemDetailResponse } from './models/WorkspaceItemDetailResponse';
export type { WorkspaceItemDetailResponseConcurrencyErrorResponse } from './models/WorkspaceItemDetailResponseConcurrencyErrorResponse';
export type { WorkspaceItemDetailResponsePagedResponse } from './models/WorkspaceItemDetailResponsePagedResponse';
export type { WorkspaceItemRelationResponse } from './models/WorkspaceItemRelationResponse';
export type { WorkspaceItemRelationsResponse } from './models/WorkspaceItemRelationsResponse';
export type { WorkspaceItemResponse } from './models/WorkspaceItemResponse';
export type { WorkspaceListItemResponse } from './models/WorkspaceListItemResponse';
export type { WorkspaceListItemResponseWorkspaceStatisticsPagedResponse } from './models/WorkspaceListItemResponseWorkspaceStatisticsPagedResponse';
export type { WorkspaceMode } from './models/WorkspaceMode';
export type { WorkspaceRole } from './models/WorkspaceRole';
export type { WorkspaceSkillResponse } from './models/WorkspaceSkillResponse';
export type { WorkspaceStatistics } from './models/WorkspaceStatistics';
export type { WorkspaceTaskDetailResponse } from './models/WorkspaceTaskDetailResponse';
export type { WorkspaceTaskDetailResponseConcurrencyErrorResponse } from './models/WorkspaceTaskDetailResponseConcurrencyErrorResponse';
export type { WorkspaceTaskDetailResponseWorkspaceTaskStatisticsPagedResponse } from './models/WorkspaceTaskDetailResponseWorkspaceTaskStatisticsPagedResponse';
export type { WorkspaceTaskResponse } from './models/WorkspaceTaskResponse';
export type { WorkspaceTaskStatistics } from './models/WorkspaceTaskStatistics';
export type { WorkspaceUserDetailResponse } from './models/WorkspaceUserDetailResponse';
export type { WorkspaceUserDetailResponseObjectPagedResponse } from './models/WorkspaceUserDetailResponseObjectPagedResponse';
export type { WorkspaceUserItem } from './models/WorkspaceUserItem';

export { ActivityService } from './services/ActivityService';
export { AdminOrganizationService } from './services/AdminOrganizationService';
export { AdminSkillService } from './services/AdminSkillService';
export { AdminTagService } from './services/AdminTagService';
export { AdminUserService } from './services/AdminUserService';
export { AdminWorkspaceService } from './services/AdminWorkspaceService';
export { BackendSpecsService } from './services/BackendSpecsService';
export { DashboardService } from './services/DashboardService';
export { EntranceAuthService } from './services/EntranceAuthService';
export { EntranceOrganizationService } from './services/EntranceOrganizationService';
export { EntrancePasswordService } from './services/EntrancePasswordService';
export { FileService } from './services/FileService';
export { FocusService } from './services/FocusService';
export { MasterService } from './services/MasterService';
export { MyService } from './services/MyService';
export { ProfileService } from './services/ProfileService';
export { TagService } from './services/TagService';
export { TaskCommentService } from './services/TaskCommentService';
export { TestEmailService } from './services/TestEmailService';
export { UserService } from './services/UserService';
export { WorkspaceService } from './services/WorkspaceService';
export { WorkspaceItemService } from './services/WorkspaceItemService';
export { WorkspaceItemTempAttachmentService } from './services/WorkspaceItemTempAttachmentService';
export { WorkspaceTaskService } from './services/WorkspaceTaskService';
