using Pecus.Libs.DB.Models;
using Pecus.Libs.DB.Models.Enums;
using System.Security.Cryptography;

namespace Pecus.Libs.DB;

/// <summary>
/// ユーザー関連エンティティの一括作成ファクトリ
/// User, UserSetting, ChatActor を一貫性をもって作成する
/// </summary>
public static class UserEntityFactory
{
    /// <summary>
    /// ユーザー作成に必要な全エンティティを生成
    /// </summary>
    /// <param name="loginId">ログインID</param>
    /// <param name="username">ユーザー名</param>
    /// <param name="email">メールアドレス</param>
    /// <param name="organizationId">組織ID</param>
    /// <param name="passwordHash">パスワードハッシュ（省略時は空文字）</param>
    /// <param name="createdByUserId">作成者ユーザーID（省略可能）</param>
    /// <param name="avatarType">アバタータイプ（省略時はAutoGenerated）</param>
    /// <param name="passwordResetToken">パスワード設定トークン（省略可能）</param>
    /// <param name="passwordResetTokenExpiresAt">トークン有効期限（省略可能）</param>
    /// <returns>User, UserSetting, ChatActor のタプル</returns>
    public static (User user, UserSetting setting, ChatActor chatActor) CreateUserEntities(
        string loginId,
        string username,
        string email,
        int organizationId,
        string passwordHash = "",
        int? createdByUserId = null,
        AvatarType avatarType = AvatarType.AutoGenerated,
        string? passwordResetToken = null,
        DateTimeOffset? passwordResetTokenExpiresAt = null)
    {
        var now = DateTimeOffset.UtcNow;

        var user = new User
        {
            LoginId = loginId,
            Username = username,
            Email = email,
            PasswordHash = passwordHash,
            OrganizationId = organizationId,
            AvatarType = avatarType,
            CreatedAt = now,
            CreatedByUserId = createdByUserId,
            IsActive = true,
            PasswordResetToken = passwordResetToken,
            PasswordResetTokenExpiresAt = passwordResetTokenExpiresAt,
        };

        var setting = new UserSetting
        {
            User = user,
            CanReceiveEmail = true,
            CanReceiveRealtimeNotification = true,
            BadgeVisibility = null,
            UpdatedAt = now,
            UpdatedByUserId = createdByUserId,
        };

        var chatActor = new ChatActor
        {
            OrganizationId = organizationId,
            ActorType = ChatActorType.User,
            User = user,
            DisplayName = username,
            AvatarType = avatarType,
            CreatedAt = now,
            UpdatedAt = now,
        };

        return (user, setting, chatActor);
    }

    /// <summary>
    /// パスワード設定トークンを生成（URL安全なBase64）
    /// </summary>
    public static string GeneratePasswordResetToken()
    {
        using var rng = RandomNumberGenerator.Create();
        var tokenBytes = new byte[32];
        rng.GetBytes(tokenBytes);
        // URL安全なBase64エンコード（+を-に、/を_に置換し、=パディングを削除）
        return Convert.ToBase64String(tokenBytes)
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');
    }

    /// <summary>
    /// パスワード設定トークンと24時間後の有効期限を生成
    /// </summary>
    public static (string token, DateTimeOffset expiresAt) GeneratePasswordResetTokenWithExpiry(int hoursValid = 24)
    {
        var token = GeneratePasswordResetToken();
        var expiresAt = DateTimeOffset.UtcNow.AddHours(hoursValid);
        return (token, expiresAt);
    }
}
