/**
 * Lexical エディタのテーマ設定
 * Notion風のスタイリングを適用
 */
import styles from "./PecusEditor.module.css";

export const pecusEditorTheme = {
  paragraph: styles.editorParagraph,
  quote: styles.editorQuote,
  heading: {
    h1: styles.editorHeadingH1,
    h2: styles.editorHeadingH2,
    h3: styles.editorHeadingH3,
    h4: styles.editorHeadingH4,
    h5: styles.editorHeadingH5,
    h6: styles.editorHeadingH6,
  },
  list: {
    nested: {
      listitem: styles.editorNestedListitem,
    },
    ol: styles.editorListOl,
    ul: styles.editorListUl,
    listitem: styles.editorListitem,
    listitemChecked: styles.editorListitemChecked,
    listitemUnchecked: styles.editorListitemUnchecked,
  },
  hashtag: styles.editorHashtag,
  image: styles.editorImage,
  link: styles.editorLink,
  table: styles.editorTable,
  tableCell: styles.editorTableCell,
  tableCellHeader: styles.editorTableCellHeader,
  tableRow: styles.editorTableRow,
  tableSelection: styles.editorTableSelection,
  text: {
    bold: styles.editorTextBold,
    code: styles.editorTextCode,
    italic: styles.editorTextItalic,
    strikethrough: styles.editorTextStrikethrough,
    subscript: styles.editorTextSubscript,
    superscript: styles.editorTextSuperscript,
    underline: styles.editorTextUnderline,
    underlineStrikethrough: styles.editorTextUnderlineStrikethrough,
  },
  code: styles.editorCode,
  codeHighlight: {
    atrule: styles.editorTokenAttr,
    attr: styles.editorTokenAttr,
    boolean: styles.editorTokenProperty,
    builtin: styles.editorTokenSelector,
    cdata: styles.editorTokenComment,
    char: styles.editorTokenSelector,
    class: styles.editorTokenFunction,
    "class-name": styles.editorTokenFunction,
    comment: styles.editorTokenComment,
    constant: styles.editorTokenProperty,
    deleted: styles.editorTokenProperty,
    doctype: styles.editorTokenComment,
    entity: styles.editorTokenOperator,
    function: styles.editorTokenFunction,
    important: styles.editorTokenVariable,
    inserted: styles.editorTokenSelector,
    keyword: styles.editorTokenAttr,
    namespace: styles.editorTokenVariable,
    number: styles.editorTokenProperty,
    operator: styles.editorTokenOperator,
    prolog: styles.editorTokenComment,
    property: styles.editorTokenProperty,
    punctuation: styles.editorTokenPunctuation,
    regex: styles.editorTokenVariable,
    selector: styles.editorTokenSelector,
    string: styles.editorTokenSelector,
    symbol: styles.editorTokenProperty,
    tag: styles.editorTokenProperty,
    url: styles.editorTokenOperator,
    variable: styles.editorTokenVariable,
  },
};
