/**
 * Lexical エディタのテーマ設定
 * Notion風のスタイリングを適用
 */
export const pecusEditorTheme = {
  paragraph: "editorParagraph",
  quote: "editorQuote",
  heading: {
    h1: "editorHeadingH1",
    h2: "editorHeadingH2",
    h3: "editorHeadingH3",
    h4: "editorHeadingH4",
    h5: "editorHeadingH5",
    h6: "editorHeadingH6",
  },
  list: {
    nested: {
      listitem: "editorNestedListitem",
    },
    ol: "editorListOl",
    ul: "editorListUl",
    listitem: "editorListitem",
    listitemChecked: "editorListitemChecked",
    listitemUnchecked: "editorListitemUnchecked",
  },
  hashtag: "editorHashtag",
  image: "editorImage",
  link: "editorLink",
  text: {
    bold: "editorTextBold",
    code: "editorTextCode",
    italic: "editorTextItalic",
    strikethrough: "editorTextStrikethrough",
    subscript: "editorTextSubscript",
    superscript: "editorTextSuperscript",
    underline: "editorTextUnderline",
    underlineStrikethrough: "editorTextUnderlineStrikethrough",
  },
  code: "editorCode",
  codeHighlight: {
    atrule: "editorTokenAttr",
    attr: "editorTokenAttr",
    boolean: "editorTokenProperty",
    builtin: "editorTokenSelector",
    cdata: "editorTokenComment",
    char: "editorTokenSelector",
    class: "editorTokenFunction",
    "class-name": "editorTokenFunction",
    comment: "editorTokenComment",
    constant: "editorTokenProperty",
    deleted: "editorTokenProperty",
    doctype: "editorTokenComment",
    entity: "editorTokenOperator",
    function: "editorTokenFunction",
    important: "editorTokenVariable",
    inserted: "editorTokenSelector",
    keyword: "editorTokenAttr",
    namespace: "editorTokenVariable",
    number: "editorTokenProperty",
    operator: "editorTokenOperator",
    prolog: "editorTokenComment",
    property: "editorTokenProperty",
    punctuation: "editorTokenPunctuation",
    regex: "editorTokenVariable",
    selector: "editorTokenSelector",
    string: "editorTokenSelector",
    symbol: "editorTokenProperty",
    tag: "editorTokenProperty",
    url: "editorTokenOperator",
    variable: "editorTokenVariable",
  },
};
