#!/bin/sh
set -eu

# Blue/Green switch procedure
# 1. Update source (git pull)
# 2. Build target image
# 3. Deploy target (excluding BackFire)
# 4. Pre-build DB Migration image
# 5. Stop other slot
# 6. DB Migration
# 7. Deploy target BackFire
# 8. Nginx Switch
#
# Options:
#   --no-build        Skip git pull and build steps (use pre-built images)
#   --skip-migration  Skip DB migration (use when migration already done)

# shellcheck disable=SC1007
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
# shellcheck disable=SC1091
. "$script_dir/lib.sh"

# オプション解析
NO_BUILD=false
SKIP_MIGRATION=false
slot=""

for arg in "$@"; do
  case "$arg" in
    --no-build)
      NO_BUILD=true
      ;;
    --skip-migration)
      SKIP_MIGRATION=true
      ;;
    blue|green)
      slot="$arg"
      ;;
    *)
      echo "Usage: $0 {blue|green} [--no-build] [--skip-migration]" >&2
      exit 2
      ;;
  esac
done

if [ -z "$slot" ]; then
  echo "Usage: $0 {blue|green} [--no-build] [--skip-migration]" >&2
  exit 2
fi

require_cmd docker

current="$(active_slot)"

slot_any_running() {
  s="$1"
  api=$(docker inspect -f '{{.State.Running}}' "pecus-webapi-$s" 2>/dev/null || true)
  fe=$(docker inspect -f '{{.State.Running}}' "pecus-frontend-$s" 2>/dev/null || true)
  bf=$(docker inspect -f '{{.State.Running}}' "pecus-backfire-$s" 2>/dev/null || true)

  if [ "$api" = "true" ] || [ "$fe" = "true" ] || [ "$bf" = "true" ]; then
    return 0
  else
    return 1
  fi
}

target="$slot"
other="green"
if [ "$target" = "green" ]; then
  other="blue"
fi

target_running=false
other_running=false

if slot_any_running "$target"; then
  target_running=true
fi
if slot_any_running "$other"; then
  other_running=true
fi

if [ "$target_running" = "true" ]; then
  echo "[Error] Target slot containers are already running: $target" >&2
  echo "        Stop them first: ./app-down.sh $target (or docker compose ... down)" >&2
  exit 2
fi

echo "[Info] Checking infra health..." >&2
if ! check_infra_healthy; then
  echo "[Error] Infra unhealthy. Run ./infra-up.sh first." >&2
  exit 3
fi

echo "[Info] Current=$current Target=$target" >&2

if [ "$NO_BUILD" = "false" ]; then
  echo "[Info] 1. Git pull" >&2
  # shellcheck disable=SC2154
  git -C "$repo_root" pull
else
  echo "[Info] 1. Git pull (SKIPPED: --no-build)" >&2
fi

echo ""
printf "[Confirm] Proceed with deployment? (yes/no) [no]: "
read -r confirm
if [ "$confirm" != "yes" ]; then
  echo "[Abort] Cancelled." >&2
  exit 0
fi

# 設定ファイル生成
ensure_env_file

if [ "$NO_BUILD" = "false" ]; then
  echo "[Info] 2. Build target: $target" >&2
  compose_app "$target" build "pecusapi-$target" "frontend-$target" "backfire-$target"
else
  echo "[Info] 2. Build target (SKIPPED: --no-build)" >&2
fi

echo "[Info] 3. Deploy target (excluding BackFire): $target" >&2
if [ "$NO_BUILD" = "false" ]; then
  compose_app "$target" up -d "pecusapi-$target" "frontend-$target"
else
  compose_app "$target" up -d --no-build "pecusapi-$target" "frontend-$target"
fi
wait_health "pecus-webapi-$target" 300
wait_running "pecus-frontend-$target" 120

if [ "$NO_BUILD" = "false" ]; then
  echo "[Info] 4. Pre-build DB Migration image" >&2
  # Clean up potential leftover dbmanager
  if docker ps -a --format '{{.Names}}' | grep -q '^pecus-dbmanager$'; then
    docker rm -f pecus-dbmanager >/dev/null 2>&1 || true
  fi
  compose_migrate build dbmanager
else
  echo "[Info] 4. Pre-build DB Migration image (SKIPPED: --no-build)" >&2
fi

if [ "$other_running" = "true" ]; then
  echo "[Info] 5. Stop old slot: $other" >&2
  compose_app "$other" stop "pecusapi-$other" "frontend-$other" "backfire-$other" || true
  compose_app "$other" rm -f "pecusapi-$other" "frontend-$other" "backfire-$other" || true
else
  echo "[Info] 5. Skip stopping old slot (not running): $other" >&2
fi

if [ "$SKIP_MIGRATION" = "true" ]; then
  echo "[Info] 6. DB Migration (SKIPPED: --skip-migration)" >&2
else
  echo "[Info] 6. DB Migration" >&2
  compose_migrate run --rm dbmanager
fi

echo "[Info] 7. Deploy target BackFire: $target" >&2
if [ "$NO_BUILD" = "false" ]; then
  compose_app "$target" up -d "backfire-$target"
else
  compose_app "$target" up -d --no-build "backfire-$target"
fi
wait_running "pecus-backfire-$target" 120

echo "[Info] 8. Switch Nginx: $target" >&2
# shellcheck disable=SC2154
conf="$bluegreen_dir/nginx/conf.d/00-active-slot.conf"
cat >"$conf" <<EOF
# Generated by ops/switch-node.sh
# blue / green
geo \$coati_active_slot {
  default $target;
}
EOF

compose_infra exec -T nginx nginx -t
compose_infra exec -T nginx nginx -s reload

echo "[Info] 9. Cleanup unused pecus resources" >&2

# Remove stopped pecus containers
# shellcheck disable=SC2046
for container in $(docker ps -a --format '{{.Names}}' 2>/dev/null | grep -E '^pecus-'); do
  running=$(docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null || echo "false")
  if [ "$running" != "true" ]; then
    docker rm -f "$container" 2>/dev/null || true
  fi
done

# Cleanup unused images (excluding snapshot-latest)
# This loop handles spaces in tags poorly, but Docker tags usually don't have spaces.
for img in $(docker images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -E '^coati-'); do
  case "$img" in
    *":snapshot-latest") continue ;;
  esac

  img_id=$(docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep "^$img " | awk '{print $2}')
  if [ -n "$img_id" ] && ! docker ps -q --filter "ancestor=$img_id" 2>/dev/null | grep -q .; then
    docker rmi "$img" 2>/dev/null || true
  fi
done

# Prune dangling images
docker images -f "dangling=true" -q 2>/dev/null | xargs -r docker rmi 2>/dev/null || true

# Prune builder cache
docker builder prune -f 2>/dev/null || true

echo "[Info] 10. Update Prometheus targets: $target" >&2
sh "$script_dir/update-prometheus-targets.sh" "$target"

echo "[OK] Switched to: $target"
