using System.Text.Json.Serialization;

namespace Pecus.Libs.DB.Models.Enums;
/// <summary>
/// アバターの種類を表す列挙型
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<AvatarType>))]
public enum AvatarType
{
    /// <summary>
    /// Gravatar
    /// </summary>
    Gravatar = 1,

    /// <summary>
    /// ユーザーアバター
    /// </summary>
    UserAvatar = 2,

    /// <summary>
    /// 自動生成アバター
    /// </summary>
    AutoGenerated = 3,
}