/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースにユーザーを参加させるリクエスト
 * @export
 * @interface AddUserToWorkspaceRequest
 */
export interface AddUserToWorkspaceRequest {
    /**
     * 参加させるユーザーID
     * @type {number}
     * @memberof AddUserToWorkspaceRequest
     */
    userId: number;
    /**
     * ワークスペース内での役割（例: Owner, Member, Guest）
     * @type {string}
     * @memberof AddUserToWorkspaceRequest
     */
    workspaceRole?: string | null;
}

/**
 * Check if a given object implements the AddUserToWorkspaceRequest interface.
 */
export function instanceOfAddUserToWorkspaceRequest(value: object): value is AddUserToWorkspaceRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AddUserToWorkspaceRequestFromJSON(json: any): AddUserToWorkspaceRequest {
    return AddUserToWorkspaceRequestFromJSONTyped(json, false);
}

export function AddUserToWorkspaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToWorkspaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'workspaceRole': json['workspaceRole'] == null ? undefined : json['workspaceRole'],
    };
}

export function AddUserToWorkspaceRequestToJSON(json: any): AddUserToWorkspaceRequest {
    return AddUserToWorkspaceRequestToJSONTyped(json, false);
}

export function AddUserToWorkspaceRequestToJSONTyped(value?: AddUserToWorkspaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'workspaceRole': value['workspaceRole'],
    };
}

