/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースアイテム関連追加リクエスト
 * @export
 * @interface AddWorkspaceItemRelationRequest
 */
export interface AddWorkspaceItemRelationRequest {
    /**
     * 関連先アイテムID
     * @type {number}
     * @memberof AddWorkspaceItemRelationRequest
     */
    toItemId: number;
    /**
     * 関連タイプ（オプション）
     * 指定可能な値: "related", "blocks", "blocked_by", "depends_on", "duplicates", "subtask_of", "parent_of", "relates_to"
     * @type {string}
     * @memberof AddWorkspaceItemRelationRequest
     */
    relationType?: string | null;
}

/**
 * Check if a given object implements the AddWorkspaceItemRelationRequest interface.
 */
export function instanceOfAddWorkspaceItemRelationRequest(value: object): value is AddWorkspaceItemRelationRequest {
    if (!('toItemId' in value) || value['toItemId'] === undefined) return false;
    return true;
}

export function AddWorkspaceItemRelationRequestFromJSON(json: any): AddWorkspaceItemRelationRequest {
    return AddWorkspaceItemRelationRequestFromJSONTyped(json, false);
}

export function AddWorkspaceItemRelationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWorkspaceItemRelationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'toItemId': json['toItemId'],
        'relationType': json['relationType'] == null ? undefined : json['relationType'],
    };
}

export function AddWorkspaceItemRelationRequestToJSON(json: any): AddWorkspaceItemRelationRequest {
    return AddWorkspaceItemRelationRequestToJSONTyped(json, false);
}

export function AddWorkspaceItemRelationRequestToJSONTyped(value?: AddWorkspaceItemRelationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toItemId': value['toItemId'],
        'relationType': value['relationType'],
    };
}

