/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceItemRelationResponse } from './WorkspaceItemRelationResponse';
import {
    WorkspaceItemRelationResponseFromJSON,
    WorkspaceItemRelationResponseFromJSONTyped,
    WorkspaceItemRelationResponseToJSON,
    WorkspaceItemRelationResponseToJSONTyped,
} from './WorkspaceItemRelationResponse';

/**
 * ワークスペースアイテム関連追加レスポンス
 * @export
 * @interface AddWorkspaceItemRelationResponse
 */
export interface AddWorkspaceItemRelationResponse {
    /**
     * 成功フラグ
     * @type {boolean}
     * @memberof AddWorkspaceItemRelationResponse
     */
    success?: boolean;
    /**
     * メッセージ
     * @type {string}
     * @memberof AddWorkspaceItemRelationResponse
     */
    message?: string | null;
    /**
     * 
     * @type {WorkspaceItemRelationResponse}
     * @memberof AddWorkspaceItemRelationResponse
     */
    relation?: WorkspaceItemRelationResponse;
}

/**
 * Check if a given object implements the AddWorkspaceItemRelationResponse interface.
 */
export function instanceOfAddWorkspaceItemRelationResponse(value: object): value is AddWorkspaceItemRelationResponse {
    return true;
}

export function AddWorkspaceItemRelationResponseFromJSON(json: any): AddWorkspaceItemRelationResponse {
    return AddWorkspaceItemRelationResponseFromJSONTyped(json, false);
}

export function AddWorkspaceItemRelationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWorkspaceItemRelationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'relation': json['relation'] == null ? undefined : WorkspaceItemRelationResponseFromJSON(json['relation']),
    };
}

export function AddWorkspaceItemRelationResponseToJSON(json: any): AddWorkspaceItemRelationResponse {
    return AddWorkspaceItemRelationResponseToJSONTyped(json, false);
}

export function AddWorkspaceItemRelationResponseToJSONTyped(value?: AddWorkspaceItemRelationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'relation': WorkspaceItemRelationResponseToJSON(value['relation']),
    };
}

