/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 権限作成リクエスト
 * @export
 * @interface CreatePermissionRequest
 */
export interface CreatePermissionRequest {
    /**
     * 権限名
     * @type {string}
     * @memberof CreatePermissionRequest
     */
    name: string;
    /**
     * 権限の説明
     * @type {string}
     * @memberof CreatePermissionRequest
     */
    description?: string | null;
    /**
     * カテゴリ
     * @type {string}
     * @memberof CreatePermissionRequest
     */
    category?: string | null;
}

/**
 * Check if a given object implements the CreatePermissionRequest interface.
 */
export function instanceOfCreatePermissionRequest(value: object): value is CreatePermissionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreatePermissionRequestFromJSON(json: any): CreatePermissionRequest {
    return CreatePermissionRequestFromJSONTyped(json, false);
}

export function CreatePermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function CreatePermissionRequestToJSON(json: any): CreatePermissionRequest {
    return CreatePermissionRequestToJSONTyped(json, false);
}

export function CreatePermissionRequestToJSONTyped(value?: CreatePermissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
    };
}

