/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * パスワードなしユーザー登録リクエスト（管理者用）
 * @export
 * @interface CreateUserWithoutPasswordRequest
 */
export interface CreateUserWithoutPasswordRequest {
    /**
     * ユーザー名
     * @type {string}
     * @memberof CreateUserWithoutPasswordRequest
     */
    username: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateUserWithoutPasswordRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CreateUserWithoutPasswordRequest interface.
 */
export function instanceOfCreateUserWithoutPasswordRequest(value: object): value is CreateUserWithoutPasswordRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateUserWithoutPasswordRequestFromJSON(json: any): CreateUserWithoutPasswordRequest {
    return CreateUserWithoutPasswordRequestFromJSONTyped(json, false);
}

export function CreateUserWithoutPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserWithoutPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
    };
}

export function CreateUserWithoutPasswordRequestToJSON(json: any): CreateUserWithoutPasswordRequest {
    return CreateUserWithoutPasswordRequestToJSONTyped(json, false);
}

export function CreateUserWithoutPasswordRequestToJSONTyped(value?: CreateUserWithoutPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
    };
}

