/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ロール作成リクエスト
 * @export
 * @interface CreateRoleRequest
 */
export interface CreateRoleRequest {
    /**
     * ロール名
     * @type {string}
     * @memberof CreateRoleRequest
     */
    name: string;
    /**
     * ロールの説明
     * @type {string}
     * @memberof CreateRoleRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateRoleRequest interface.
 */
export function instanceOfCreateRoleRequest(value: object): value is CreateRoleRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateRoleRequestFromJSON(json: any): CreateRoleRequest {
    return CreateRoleRequestFromJSONTyped(json, false);
}

export function CreateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateRoleRequestToJSON(json: any): CreateRoleRequest {
    return CreateRoleRequestToJSONTyped(json, false);
}

export function CreateRoleRequestToJSONTyped(value?: CreateRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

