/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ジャンル一覧用レスポンス
 * @export
 * @interface GenreListItemResponse
 */
export interface GenreListItemResponse {
    /**
     * ジャンルID
     * @type {number}
     * @memberof GenreListItemResponse
     */
    id?: number;
    /**
     * ジャンル名
     * @type {string}
     * @memberof GenreListItemResponse
     */
    name: string | null;
    /**
     * ジャンルの説明
     * @type {string}
     * @memberof GenreListItemResponse
     */
    description?: string | null;
    /**
     * ジャンルアイコン
     * @type {string}
     * @memberof GenreListItemResponse
     */
    icon?: string | null;
    /**
     * 表示順
     * @type {number}
     * @memberof GenreListItemResponse
     */
    displayOrder?: number;
    /**
     * このジャンルを使用しているワークスペース数
     * @type {number}
     * @memberof GenreListItemResponse
     */
    workspaceCount?: number;
    /**
     * 有効フラグ
     * @type {boolean}
     * @memberof GenreListItemResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the GenreListItemResponse interface.
 */
export function instanceOfGenreListItemResponse(value: object): value is GenreListItemResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GenreListItemResponseFromJSON(json: any): GenreListItemResponse {
    return GenreListItemResponseFromJSONTyped(json, false);
}

export function GenreListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenreListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
        'workspaceCount': json['workspaceCount'] == null ? undefined : json['workspaceCount'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function GenreListItemResponseToJSON(json: any): GenreListItemResponse {
    return GenreListItemResponseToJSONTyped(json, false);
}

export function GenreListItemResponseToJSONTyped(value?: GenreListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'displayOrder': value['displayOrder'],
        'workspaceCount': value['workspaceCount'],
        'isActive': value['isActive'],
    };
}

