/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 組織詳細レスポンス
 * @export
 * @interface OrganizationDetailResponse
 */
export interface OrganizationDetailResponse {
    /**
     * 組織ID
     * @type {number}
     * @memberof OrganizationDetailResponse
     */
    id?: number;
    /**
     * 組織名
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    name: string | null;
    /**
     * 組織コード
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    code?: string | null;
    /**
     * 組織の説明
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    description?: string | null;
    /**
     * 代表者名
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    representativeName?: string | null;
    /**
     * 電話番号
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    phoneNumber: string | null;
    /**
     * メールアドレス
     * @type {string}
     * @memberof OrganizationDetailResponse
     */
    email?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof OrganizationDetailResponse
     */
    createdAt?: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof OrganizationDetailResponse
     */
    updatedAt?: Date | null;
    /**
     * アクティブフラグ
     * @type {boolean}
     * @memberof OrganizationDetailResponse
     */
    isActive?: boolean;
    /**
     * 所属ユーザー数
     * @type {number}
     * @memberof OrganizationDetailResponse
     */
    userCount?: number;
}

/**
 * Check if a given object implements the OrganizationDetailResponse interface.
 */
export function instanceOfOrganizationDetailResponse(value: object): value is OrganizationDetailResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    return true;
}

export function OrganizationDetailResponseFromJSON(json: any): OrganizationDetailResponse {
    return OrganizationDetailResponseFromJSONTyped(json, false);
}

export function OrganizationDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'representativeName': json['representativeName'] == null ? undefined : json['representativeName'],
        'phoneNumber': json['phoneNumber'],
        'email': json['email'] == null ? undefined : json['email'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'userCount': json['userCount'] == null ? undefined : json['userCount'],
    };
}

export function OrganizationDetailResponseToJSON(json: any): OrganizationDetailResponse {
    return OrganizationDetailResponseToJSONTyped(json, false);
}

export function OrganizationDetailResponseToJSONTyped(value?: OrganizationDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'description': value['description'],
        'representativeName': value['representativeName'],
        'phoneNumber': value['phoneNumber'],
        'email': value['email'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'isActive': value['isActive'],
        'userCount': value['userCount'],
    };
}

