/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 組織情報レスポンス（簡易版）
 * @export
 * @interface OrganizationInfoResponse
 */
export interface OrganizationInfoResponse {
    /**
     * 組織ID
     * @type {number}
     * @memberof OrganizationInfoResponse
     */
    id?: number;
    /**
     * 組織名
     * @type {string}
     * @memberof OrganizationInfoResponse
     */
    name: string | null;
    /**
     * 組織コード
     * @type {string}
     * @memberof OrganizationInfoResponse
     */
    code?: string | null;
}

/**
 * Check if a given object implements the OrganizationInfoResponse interface.
 */
export function instanceOfOrganizationInfoResponse(value: object): value is OrganizationInfoResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationInfoResponseFromJSON(json: any): OrganizationInfoResponse {
    return OrganizationInfoResponseFromJSONTyped(json, false);
}

export function OrganizationInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function OrganizationInfoResponseToJSON(json: any): OrganizationInfoResponse {
    return OrganizationInfoResponseToJSONTyped(json, false);
}

export function OrganizationInfoResponseToJSONTyped(value?: OrganizationInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
    };
}

