/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleInfoResponse } from './RoleInfoResponse';
import {
    RoleInfoResponseFromJSON,
    RoleInfoResponseFromJSONTyped,
    RoleInfoResponseToJSON,
    RoleInfoResponseToJSONTyped,
} from './RoleInfoResponse';

/**
 * 権限詳細レスポンス（ロールを含む）
 * @export
 * @interface PermissionDetailResponse
 */
export interface PermissionDetailResponse {
    /**
     * 権限ID
     * @type {number}
     * @memberof PermissionDetailResponse
     */
    id?: number;
    /**
     * 権限名
     * @type {string}
     * @memberof PermissionDetailResponse
     */
    name: string | null;
    /**
     * 権限の説明
     * @type {string}
     * @memberof PermissionDetailResponse
     */
    description?: string | null;
    /**
     * 権限カテゴリ
     * @type {string}
     * @memberof PermissionDetailResponse
     */
    category?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof PermissionDetailResponse
     */
    createdAt?: Date;
    /**
     * この権限を持つロール一覧
     * @type {Array<RoleInfoResponse>}
     * @memberof PermissionDetailResponse
     */
    roles?: Array<RoleInfoResponse> | null;
}

/**
 * Check if a given object implements the PermissionDetailResponse interface.
 */
export function instanceOfPermissionDetailResponse(value: object): value is PermissionDetailResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PermissionDetailResponseFromJSON(json: any): PermissionDetailResponse {
    return PermissionDetailResponseFromJSONTyped(json, false);
}

export function PermissionDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(RoleInfoResponseFromJSON)),
    };
}

export function PermissionDetailResponseToJSON(json: any): PermissionDetailResponse {
    return PermissionDetailResponseToJSONTyped(json, false);
}

export function PermissionDetailResponseToJSONTyped(value?: PermissionDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(RoleInfoResponseToJSON)),
    };
}

