/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 権限情報レスポンス
 * @export
 * @interface PermissionResponse
 */
export interface PermissionResponse {
    /**
     * 権限ID
     * @type {number}
     * @memberof PermissionResponse
     */
    id?: number;
    /**
     * 権限名
     * @type {string}
     * @memberof PermissionResponse
     */
    name: string | null;
    /**
     * 権限の説明
     * @type {string}
     * @memberof PermissionResponse
     */
    description?: string | null;
    /**
     * 権限カテゴリ
     * @type {string}
     * @memberof PermissionResponse
     */
    category?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof PermissionResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the PermissionResponse interface.
 */
export function instanceOfPermissionResponse(value: object): value is PermissionResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PermissionResponseFromJSON(json: any): PermissionResponse {
    return PermissionResponseFromJSONTyped(json, false);
}

export function PermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'category': json['category'] == null ? undefined : json['category'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function PermissionResponseToJSON(json: any): PermissionResponse {
    return PermissionResponseToJSONTyped(json, false);
}

export function PermissionResponseToJSONTyped(value?: PermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'category': value['category'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

