/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * ランキング項目DTO
 */
export type RankingItemDto = {
    /**
     * 順位（1〜3）
     */
    rank: number;
    /**
     * ユーザーの内部ID
     */
    userInternalId: number;
    /**
     * ユーザーの表示用ID（visibleId）
     */
    userId: string;
    /**
     * ユーザー表示名
     */
    displayName: string;
    /**
     * アバターURL（Gravatar / UserAvatar / AutoGenerated いずれかのURL）
     */
    avatarUrl: string;
    /**
     * スコア（各ランキング種別に応じた値）
     * - 難易度ランキング: 難易度スコア合計
     * - 取得数ランキング: バッジ取得数
     * - 成長速度ランキング: 成長スコア（バッジ数/活動日数×100）
     */
    score: number;
    /**
     * バッジ取得総数（参考表示用）
     */
    badgeCount: number;
};

