/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipientRequest
 */
export interface RecipientRequest {
    /**
     * 
     * @type {string}
     * @memberof RecipientRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the RecipientRequest interface.
 */
export function instanceOfRecipientRequest(value: object): value is RecipientRequest {
    return true;
}

export function RecipientRequestFromJSON(json: any): RecipientRequest {
    return RecipientRequestFromJSONTyped(json, false);
}

export function RecipientRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function RecipientRequestToJSON(json: any): RecipientRequest {
    return RecipientRequestToJSONTyped(json, false);
}

export function RecipientRequestToJSONTyped(value?: RecipientRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

