/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionDetailInfoResponse } from './PermissionDetailInfoResponse';
import {
    PermissionDetailInfoResponseFromJSON,
    PermissionDetailInfoResponseFromJSONTyped,
    PermissionDetailInfoResponseToJSON,
    PermissionDetailInfoResponseToJSONTyped,
} from './PermissionDetailInfoResponse';

/**
 * ロール詳細レスポンス（権限を含む）
 * @export
 * @interface RoleDetailResponse
 */
export interface RoleDetailResponse {
    /**
     * ロールID
     * @type {number}
     * @memberof RoleDetailResponse
     */
    id?: number;
    /**
     * ロール名
     * @type {string}
     * @memberof RoleDetailResponse
     */
    name: string | null;
    /**
     * ロールの説明
     * @type {string}
     * @memberof RoleDetailResponse
     */
    description?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof RoleDetailResponse
     */
    createdAt?: Date;
    /**
     * ロールが持つ権限一覧
     * @type {Array<PermissionDetailInfoResponse>}
     * @memberof RoleDetailResponse
     */
    permissions?: Array<PermissionDetailInfoResponse> | null;
}

/**
 * Check if a given object implements the RoleDetailResponse interface.
 */
export function instanceOfRoleDetailResponse(value: object): value is RoleDetailResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoleDetailResponseFromJSON(json: any): RoleDetailResponse {
    return RoleDetailResponseFromJSONTyped(json, false);
}

export function RoleDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(PermissionDetailInfoResponseFromJSON)),
    };
}

export function RoleDetailResponseToJSON(json: any): RoleDetailResponse {
    return RoleDetailResponseToJSONTyped(json, false);
}

export function RoleDetailResponseToJSONTyped(value?: RoleDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(PermissionDetailInfoResponseToJSON)),
    };
}

