/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ロールリスト項目レスポンス
 * @export
 * @interface RoleListItemResponse
 */
export interface RoleListItemResponse {
    /**
     * ロールID
     * @type {number}
     * @memberof RoleListItemResponse
     */
    id?: number;
    /**
     * ロール名
     * @type {string}
     * @memberof RoleListItemResponse
     */
    name: string | null;
    /**
     * ロールの説明
     * @type {string}
     * @memberof RoleListItemResponse
     */
    description?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof RoleListItemResponse
     */
    createdAt?: Date;
    /**
     * ロールが持つ権限数
     * @type {number}
     * @memberof RoleListItemResponse
     */
    permissionCount?: number;
}

/**
 * Check if a given object implements the RoleListItemResponse interface.
 */
export function instanceOfRoleListItemResponse(value: object): value is RoleListItemResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoleListItemResponseFromJSON(json: any): RoleListItemResponse {
    return RoleListItemResponseFromJSONTyped(json, false);
}

export function RoleListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'permissionCount': json['permissionCount'] == null ? undefined : json['permissionCount'],
    };
}

export function RoleListItemResponseToJSON(json: any): RoleListItemResponse {
    return RoleListItemResponseToJSONTyped(json, false);
}

export function RoleListItemResponseToJSONTyped(value?: RoleListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'permissionCount': value['permissionCount'],
    };
}

