/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ロール情報レスポンス（簡易版）
 * @export
 * @interface RoleInfoResponse
 */
export interface RoleInfoResponse {
    /**
     * ロールID
     * @type {number}
     * @memberof RoleInfoResponse
     */
    id?: number;
    /**
     * ロール名
     * @type {string}
     * @memberof RoleInfoResponse
     */
    name: string | null;
}

/**
 * Check if a given object implements the RoleInfoResponse interface.
 */
export function instanceOfRoleInfoResponse(value: object): value is RoleInfoResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RoleInfoResponseFromJSON(json: any): RoleInfoResponse {
    return RoleInfoResponseFromJSONTyped(json, false);
}

export function RoleInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function RoleInfoResponseToJSON(json: any): RoleInfoResponse {
    return RoleInfoResponseToJSONTyped(json, false);
}

export function RoleInfoResponseToJSONTyped(value?: RoleInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

