/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * アクティブ状態設定リクエスト
 * @export
 * @interface SetActiveStatusRequest
 */
export interface SetActiveStatusRequest {
    /**
     * アクティブ状態（true: 有効, false: 無効）
     * @type {boolean}
     * @memberof SetActiveStatusRequest
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the SetActiveStatusRequest interface.
 */
export function instanceOfSetActiveStatusRequest(value: object): value is SetActiveStatusRequest {
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function SetActiveStatusRequestFromJSON(json: any): SetActiveStatusRequest {
    return SetActiveStatusRequestFromJSONTyped(json, false);
}

export function SetActiveStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetActiveStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['isActive'],
    };
}

export function SetActiveStatusRequestToJSON(json: any): SetActiveStatusRequest {
    return SetActiveStatusRequestToJSONTyped(json, false);
}

export function SetActiveStatusRequestToJSONTyped(value?: SetActiveStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isActive': value['isActive'],
    };
}

