/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ロールに権限を設定するリクエスト
 * @export
 * @interface SetPermissionsToRoleRequest
 */
export interface SetPermissionsToRoleRequest {
    /**
     * 設定する権限IDのリスト。既存の権限をすべて置き換えます。
     * 空のリストまたはnullを指定するとすべての権限が削除されます。
     * @type {Array<number>}
     * @memberof SetPermissionsToRoleRequest
     */
    permissionIds?: Array<number> | null;
}

/**
 * Check if a given object implements the SetPermissionsToRoleRequest interface.
 */
export function instanceOfSetPermissionsToRoleRequest(value: object): value is SetPermissionsToRoleRequest {
    return true;
}

export function SetPermissionsToRoleRequestFromJSON(json: any): SetPermissionsToRoleRequest {
    return SetPermissionsToRoleRequestFromJSONTyped(json, false);
}

export function SetPermissionsToRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPermissionsToRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'permissionIds': json['permissionIds'] == null ? undefined : json['permissionIds'],
    };
}

export function SetPermissionsToRoleRequestToJSON(json: any): SetPermissionsToRoleRequest {
    return SetPermissionsToRoleRequestToJSONTyped(json, false);
}

export function SetPermissionsToRoleRequestToJSONTyped(value?: SetPermissionsToRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissionIds': value['permissionIds'],
    };
}

