/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request DTO for setting all tags on a workspace item
 * @export
 * @interface SetTagsToItemRequest
 */
export interface SetTagsToItemRequest {
    /**
     * List of tag names to set on the item. Replaces all existing tags.
     * Tags will be auto-created in the organization if they don't exist.
     * Empty list or null will remove all tags.
     * @type {Array<string>}
     * @memberof SetTagsToItemRequest
     */
    tagNames?: Array<string> | null;
}

/**
 * Check if a given object implements the SetTagsToItemRequest interface.
 */
export function instanceOfSetTagsToItemRequest(value: object): value is SetTagsToItemRequest {
    return true;
}

export function SetTagsToItemRequestFromJSON(json: any): SetTagsToItemRequest {
    return SetTagsToItemRequestFromJSONTyped(json, false);
}

export function SetTagsToItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetTagsToItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tagNames': json['tagNames'] == null ? undefined : json['tagNames'],
    };
}

export function SetTagsToItemRequestToJSON(json: any): SetTagsToItemRequest {
    return SetTagsToItemRequestToJSONTyped(json, false);
}

export function SetTagsToItemRequestToJSONTyped(value?: SetTagsToItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tagNames': value['tagNames'],
    };
}

