/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * スキル設定リクエスト
 * @export
 * @interface SetUserSkillsRequest
 */
export interface SetUserSkillsRequest {
    /**
     * スキルIDのリスト
     * @type {Array<number>}
     * @memberof SetUserSkillsRequest
     */
    skillIds: Array<number> | null;
}

/**
 * Check if a given object implements the SetUserSkillsRequest interface.
 */
export function instanceOfSetUserSkillsRequest(value: object): value is SetUserSkillsRequest {
    if (!('skillIds' in value) || value['skillIds'] === undefined) return false;
    return true;
}

export function SetUserSkillsRequestFromJSON(json: any): SetUserSkillsRequest {
    return SetUserSkillsRequestFromJSONTyped(json, false);
}

export function SetUserSkillsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserSkillsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'skillIds': json['skillIds'] == null ? null : json['skillIds'],
    };
}

export function SetUserSkillsRequestToJSON(json: any): SetUserSkillsRequest {
    return SetUserSkillsRequestToJSONTyped(json, false);
}

export function SetUserSkillsRequestToJSONTyped(value?: SetUserSkillsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skillIds': value['skillIds'],
    };
}

