/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ユーザーパスワード設定リクエスト
 * @export
 * @interface SetUserPasswordRequest
 */
export interface SetUserPasswordRequest {
    /**
     * パスワード設定トークン（メールで送信されたもの）
     * @type {string}
     * @memberof SetUserPasswordRequest
     */
    token: string;
    /**
     * 新しいパスワード
     * @type {string}
     * @memberof SetUserPasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the SetUserPasswordRequest interface.
 */
export function instanceOfSetUserPasswordRequest(value: object): value is SetUserPasswordRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SetUserPasswordRequestFromJSON(json: any): SetUserPasswordRequest {
    return SetUserPasswordRequestFromJSONTyped(json, false);
}

export function SetUserPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'password': json['password'],
    };
}

export function SetUserPasswordRequestToJSON(json: any): SetUserPasswordRequest {
    return SetUserPasswordRequestToJSONTyped(json, false);
}

export function SetUserPasswordRequestToJSONTyped(value?: SetUserPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'password': value['password'],
    };
}

