/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * アクティブ状態設定リクエスト
 * @export
 * @interface SetUserActiveStatusRequest
 */
export interface SetUserActiveStatusRequest {
    /**
     * アクティブ状態（true: 有効, false: 無効）
     * @type {boolean}
     * @memberof SetUserActiveStatusRequest
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the SetUserActiveStatusRequest interface.
 */
export function instanceOfSetUserActiveStatusRequest(value: object): value is SetUserActiveStatusRequest {
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function SetUserActiveStatusRequestFromJSON(json: any): SetUserActiveStatusRequest {
    return SetUserActiveStatusRequestFromJSONTyped(json, false);
}

export function SetUserActiveStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserActiveStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['isActive'],
    };
}

export function SetUserActiveStatusRequestToJSON(json: any): SetUserActiveStatusRequest {
    return SetUserActiveStatusRequestToJSONTyped(json, false);
}

export function SetUserActiveStatusRequestToJSONTyped(value?: SetUserActiveStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isActive': value['isActive'],
    };
}

