/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 成功メッセージレスポンス
 * @export
 * @interface SuccessResponse
 */
export interface SuccessResponse {
    /**
     * HTTPステータスコード
     * @type {number}
     * @memberof SuccessResponse
     */
    statusCode?: number;
    /**
     * 成功メッセージ
     * @type {string}
     * @memberof SuccessResponse
     */
    message: string | null;
}

/**
 * Check if a given object implements the SuccessResponse interface.
 */
export function instanceOfSuccessResponse(value: object): value is SuccessResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SuccessResponseFromJSON(json: any): SuccessResponse {
    return SuccessResponseFromJSONTyped(json, false);
}

export function SuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'],
    };
}

export function SuccessResponseToJSON(json: any): SuccessResponse {
    return SuccessResponseToJSONTyped(json, false);
}

export function SuccessResponseToJSONTyped(value?: SuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

