/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * タグ詳細レスポンス
 * @export
 * @interface TagDetailResponse
 */
export interface TagDetailResponse {
    /**
     * タグID
     * @type {number}
     * @memberof TagDetailResponse
     */
    id?: number;
    /**
     * 組織ID
     * @type {number}
     * @memberof TagDetailResponse
     */
    organizationId?: number;
    /**
     * タグ名
     * @type {string}
     * @memberof TagDetailResponse
     */
    name?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof TagDetailResponse
     */
    createdAt?: Date;
    /**
     * 作成者ユーザーID
     * @type {number}
     * @memberof TagDetailResponse
     */
    createdByUserId?: number;
    /**
     * 作成者ユーザー名
     * @type {string}
     * @memberof TagDetailResponse
     */
    createdByUsername?: string | null;
    /**
     * 更新日時
     * @type {Date}
     * @memberof TagDetailResponse
     */
    updatedAt?: Date;
    /**
     * このタグが付与されているアイテム数
     * @type {number}
     * @memberof TagDetailResponse
     */
    itemCount?: number;
}

/**
 * Check if a given object implements the TagDetailResponse interface.
 */
export function instanceOfTagDetailResponse(value: object): value is TagDetailResponse {
    return true;
}

export function TagDetailResponseFromJSON(json: any): TagDetailResponse {
    return TagDetailResponseFromJSONTyped(json, false);
}

export function TagDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdByUserId': json['createdByUserId'] == null ? undefined : json['createdByUserId'],
        'createdByUsername': json['createdByUsername'] == null ? undefined : json['createdByUsername'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'itemCount': json['itemCount'] == null ? undefined : json['itemCount'],
    };
}

export function TagDetailResponseToJSON(json: any): TagDetailResponse {
    return TagDetailResponseToJSONTyped(json, false);
}

export function TagDetailResponseToJSONTyped(value?: TagDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdByUserId': value['createdByUserId'],
        'createdByUsername': value['createdByUsername'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'itemCount': value['itemCount'],
    };
}

