/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * プロフィール更新リクエスト
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * ユーザー名
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    username?: string | null;
    /**
     * アバタータイプ
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    avatarType?: string | null;
    /**
     * アバターURL
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    avatarUrl?: string | null;
    /**
     * スキルIDリスト
     * @type {Array<number>}
     * @memberof UpdateProfileRequest
     */
    skillIds?: Array<number> | null;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'avatarType': json['avatarType'] == null ? undefined : json['avatarType'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'skillIds': json['skillIds'] == null ? undefined : json['skillIds'],
    };
}

export function UpdateProfileRequestToJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestToJSONTyped(json, false);
}

export function UpdateProfileRequestToJSONTyped(value?: UpdateProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'avatarType': value['avatarType'],
        'avatarUrl': value['avatarUrl'],
        'skillIds': value['skillIds'],
    };
}

