/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ジャンル更新リクエスト
 * @export
 * @interface UpdateGenreRequest
 */
export interface UpdateGenreRequest {
    /**
     * ジャンル名
     * @type {string}
     * @memberof UpdateGenreRequest
     */
    name?: string | null;
    /**
     * ジャンルの説明
     * @type {string}
     * @memberof UpdateGenreRequest
     */
    description?: string | null;
    /**
     * ジャンルアイコン
     * @type {string}
     * @memberof UpdateGenreRequest
     */
    icon?: string | null;
    /**
     * 表示順
     * @type {number}
     * @memberof UpdateGenreRequest
     */
    displayOrder?: number | null;
}

/**
 * Check if a given object implements the UpdateGenreRequest interface.
 */
export function instanceOfUpdateGenreRequest(value: object): value is UpdateGenreRequest {
    return true;
}

export function UpdateGenreRequestFromJSON(json: any): UpdateGenreRequest {
    return UpdateGenreRequestFromJSONTyped(json, false);
}

export function UpdateGenreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGenreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'displayOrder': json['displayOrder'] == null ? undefined : json['displayOrder'],
    };
}

export function UpdateGenreRequestToJSON(json: any): UpdateGenreRequest {
    return UpdateGenreRequestToJSONTyped(json, false);
}

export function UpdateGenreRequestToJSONTyped(value?: UpdateGenreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'icon': value['icon'],
        'displayOrder': value['displayOrder'],
    };
}

