/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースアイテムステータス更新リクエスト
 * @export
 * @interface UpdateWorkspaceItemStatusRequest
 */
export interface UpdateWorkspaceItemStatusRequest {
    /**
     * 下書き中フラグ
     * @type {boolean}
     * @memberof UpdateWorkspaceItemStatusRequest
     */
    isDraft?: boolean | null;
    /**
     * アーカイブフラグ
     * @type {boolean}
     * @memberof UpdateWorkspaceItemStatusRequest
     */
    isArchived?: boolean | null;
}

/**
 * Check if a given object implements the UpdateWorkspaceItemStatusRequest interface.
 */
export function instanceOfUpdateWorkspaceItemStatusRequest(value: object): value is UpdateWorkspaceItemStatusRequest {
    return true;
}

export function UpdateWorkspaceItemStatusRequestFromJSON(json: any): UpdateWorkspaceItemStatusRequest {
    return UpdateWorkspaceItemStatusRequestFromJSONTyped(json, false);
}

export function UpdateWorkspaceItemStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWorkspaceItemStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isDraft': json['isDraft'] == null ? undefined : json['isDraft'],
        'isArchived': json['isArchived'] == null ? undefined : json['isArchived'],
    };
}

export function UpdateWorkspaceItemStatusRequestToJSON(json: any): UpdateWorkspaceItemStatusRequest {
    return UpdateWorkspaceItemStatusRequestToJSONTyped(json, false);
}

export function UpdateWorkspaceItemStatusRequestToJSONTyped(value?: UpdateWorkspaceItemStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isDraft': value['isDraft'],
        'isArchived': value['isArchived'],
    };
}

