/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * タグ更新リクエスト
 * @export
 * @interface UpdateTagRequest
 */
export interface UpdateTagRequest {
    /**
     * タグ名
     * @type {string}
     * @memberof UpdateTagRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateTagRequest interface.
 */
export function instanceOfUpdateTagRequest(value: object): value is UpdateTagRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateTagRequestFromJSON(json: any): UpdateTagRequest {
    return UpdateTagRequestFromJSONTyped(json, false);
}

export function UpdateTagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTagRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateTagRequestToJSON(json: any): UpdateTagRequest {
    return UpdateTagRequestToJSONTyped(json, false);
}

export function UpdateTagRequestToJSONTyped(value?: UpdateTagRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

