/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * メールアドレス変更リクエスト
 * @export
 * @interface UpdateEmailRequest
 */
export interface UpdateEmailRequest {
    /**
     * 新しいメールアドレス
     * @type {string}
     * @memberof UpdateEmailRequest
     */
    newEmail: string;
}

/**
 * Check if a given object implements the UpdateEmailRequest interface.
 */
export function instanceOfUpdateEmailRequest(value: object): value is UpdateEmailRequest {
    if (!('newEmail' in value) || value['newEmail'] === undefined) return false;
    return true;
}

export function UpdateEmailRequestFromJSON(json: any): UpdateEmailRequest {
    return UpdateEmailRequestFromJSONTyped(json, false);
}

export function UpdateEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newEmail': json['newEmail'],
    };
}

export function UpdateEmailRequestToJSON(json: any): UpdateEmailRequest {
    return UpdateEmailRequestToJSONTyped(json, false);
}

export function UpdateEmailRequestToJSONTyped(value?: UpdateEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newEmail': value['newEmail'],
    };
}

