/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ユーザーリスト項目レスポンス
 * @export
 * @interface UserListItemResponse
 */
export interface UserListItemResponse {
    /**
     * ユーザーID
     * @type {number}
     * @memberof UserListItemResponse
     */
    id?: number;
    /**
     * ログインID
     * @type {string}
     * @memberof UserListItemResponse
     */
    loginId: string | null;
    /**
     * ユーザー名
     * @type {string}
     * @memberof UserListItemResponse
     */
    username: string | null;
    /**
     * メールアドレス
     * @type {string}
     * @memberof UserListItemResponse
     */
    email: string | null;
    /**
     * アバタータイプ
     * @type {string}
     * @memberof UserListItemResponse
     */
    avatarType?: string | null;
    /**
     * アイデンティティアイコンURL
     * @type {string}
     * @memberof UserListItemResponse
     */
    identityIconUrl?: string | null;
    /**
     * アクティブフラグ
     * @type {boolean}
     * @memberof UserListItemResponse
     */
    isActive?: boolean;
    /**
     * 作成日時
     * @type {Date}
     * @memberof UserListItemResponse
     */
    createdAt?: Date;
    /**
     * 最終ログイン日時
     * @type {Date}
     * @memberof UserListItemResponse
     */
    lastLoginAt?: Date | null;
    /**
     * ユーザーが持つロール数
     * @type {number}
     * @memberof UserListItemResponse
     */
    roleCount?: number;
}

/**
 * Check if a given object implements the UserListItemResponse interface.
 */
export function instanceOfUserListItemResponse(value: object): value is UserListItemResponse {
    if (!('loginId' in value) || value['loginId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UserListItemResponseFromJSON(json: any): UserListItemResponse {
    return UserListItemResponseFromJSONTyped(json, false);
}

export function UserListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'loginId': json['loginId'],
        'username': json['username'],
        'email': json['email'],
        'avatarType': json['avatarType'] == null ? undefined : json['avatarType'],
        'identityIconUrl': json['identityIconUrl'] == null ? undefined : json['identityIconUrl'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'lastLoginAt': json['lastLoginAt'] == null ? undefined : (new Date(json['lastLoginAt'])),
        'roleCount': json['roleCount'] == null ? undefined : json['roleCount'],
    };
}

export function UserListItemResponseToJSON(json: any): UserListItemResponse {
    return UserListItemResponseToJSONTyped(json, false);
}

export function UserListItemResponseToJSONTyped(value?: UserListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'loginId': value['loginId'],
        'username': value['username'],
        'email': value['email'],
        'avatarType': value['avatarType'],
        'identityIconUrl': value['identityIconUrl'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'lastLoginAt': value['lastLoginAt'] == null ? value['lastLoginAt'] : value['lastLoginAt'].toISOString(),
        'roleCount': value['roleCount'],
    };
}

