/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { AvatarType } from './AvatarType';
import type { UserRoleResponse } from './UserRoleResponse';
import type { UserSkillResponse } from './UserSkillResponse';
/**
 * ユーザー情報レスポンス
 */
export type UserResponse = {
    /**
     * ユーザーID
     */
    id: number;
    /**
     * ログインID
     */
    loginId: string;
    /**
     * ユーザー名
     */
    username: string;
    /**
     * メールアドレス
     */
    email: string;
    avatarType?: AvatarType;
    /**
     * ユーザーがアップロードしたカスタムアバター画像のパス（ファイル名）
     * AvatarTypeに関わらず、過去にアップロードされたファイルのパスを保持（再利用可能）
     */
    userAvatarPath?: string | null;
    /**
     * アイデンティティアイコンURL（表示用）
     * AvatarTypeに応じて適切なURL（Gravatar/UserAvatar/AutoGenerated）が設定される
     * 必ず有効なURLが返されるため、クライアント側でnullチェック不要
     */
    identityIconUrl: string;
    /**
     * ユーザーのロール一覧
     */
    roles: Array<UserRoleResponse>;
    /**
     * ユーザーのスキル一覧
     */
    skills?: Array<UserSkillResponse> | null;
    /**
     * 管理者権限を持つかどうか
     */
    isAdmin: boolean;
    /**
     * アクティブなユーザーかどうか
     */
    isActive?: boolean;
    /**
     * 作成日時
     */
    createdAt?: string;
    /**
     * ユーザーの楽観的ロック用RowVersion
     */
    rowVersion: number;
};

