/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceItemDetailResponse } from './WorkspaceItemDetailResponse';
import {
    WorkspaceItemDetailResponseFromJSON,
    WorkspaceItemDetailResponseFromJSONTyped,
    WorkspaceItemDetailResponseToJSON,
    WorkspaceItemDetailResponseToJSONTyped,
} from './WorkspaceItemDetailResponse';

/**
 * ページネーション付きレスポンス
 * @export
 * @interface WorkspaceItemDetailResponsePagedResponse
 */
export interface WorkspaceItemDetailResponsePagedResponse {
    /**
     * データのリスト
     * @type {Array<WorkspaceItemDetailResponse>}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    data: Array<WorkspaceItemDetailResponse> | null;
    /**
     * 現在のページ番号（1から始まる）
     * @type {number}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    currentPage?: number;
    /**
     * 1ページあたりのアイテム数
     * @type {number}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    pageSize?: number;
    /**
     * 総アイテム数
     * @type {number}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    totalCount?: number;
    /**
     * 総ページ数
     * @type {number}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    totalPages?: number;
    /**
     * 前のページが存在するか
     * @type {boolean}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    hasPreviousPage?: boolean;
    /**
     * 次のページが存在するか
     * @type {boolean}
     * @memberof WorkspaceItemDetailResponsePagedResponse
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the WorkspaceItemDetailResponsePagedResponse interface.
 */
export function instanceOfWorkspaceItemDetailResponsePagedResponse(value: object): value is WorkspaceItemDetailResponsePagedResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WorkspaceItemDetailResponsePagedResponseFromJSON(json: any): WorkspaceItemDetailResponsePagedResponse {
    return WorkspaceItemDetailResponsePagedResponseFromJSONTyped(json, false);
}

export function WorkspaceItemDetailResponsePagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceItemDetailResponsePagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(WorkspaceItemDetailResponseFromJSON)),
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function WorkspaceItemDetailResponsePagedResponseToJSON(json: any): WorkspaceItemDetailResponsePagedResponse {
    return WorkspaceItemDetailResponsePagedResponseToJSONTyped(json, false);
}

export function WorkspaceItemDetailResponsePagedResponseToJSONTyped(value?: WorkspaceItemDetailResponsePagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(WorkspaceItemDetailResponseToJSON)),
        'currentPage': value['currentPage'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

