/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceListItemResponse } from './WorkspaceListItemResponse';
import {
    WorkspaceListItemResponseFromJSON,
    WorkspaceListItemResponseFromJSONTyped,
    WorkspaceListItemResponseToJSON,
    WorkspaceListItemResponseToJSONTyped,
} from './WorkspaceListItemResponse';

/**
 * ページネーション付きレスポンス
 * @export
 * @interface WorkspaceListItemResponsePagedResponse
 */
export interface WorkspaceListItemResponsePagedResponse {
    /**
     * データのリスト
     * @type {Array<WorkspaceListItemResponse>}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    data: Array<WorkspaceListItemResponse> | null;
    /**
     * 現在のページ番号（1から始まる）
     * @type {number}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    currentPage?: number;
    /**
     * 1ページあたりのアイテム数
     * @type {number}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    pageSize?: number;
    /**
     * 総アイテム数
     * @type {number}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    totalCount?: number;
    /**
     * 総ページ数
     * @type {number}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    totalPages?: number;
    /**
     * 前のページが存在するか
     * @type {boolean}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    hasPreviousPage?: boolean;
    /**
     * 次のページが存在するか
     * @type {boolean}
     * @memberof WorkspaceListItemResponsePagedResponse
     */
    hasNextPage?: boolean;
}

/**
 * Check if a given object implements the WorkspaceListItemResponsePagedResponse interface.
 */
export function instanceOfWorkspaceListItemResponsePagedResponse(value: object): value is WorkspaceListItemResponsePagedResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WorkspaceListItemResponsePagedResponseFromJSON(json: any): WorkspaceListItemResponsePagedResponse {
    return WorkspaceListItemResponsePagedResponseFromJSONTyped(json, false);
}

export function WorkspaceListItemResponsePagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceListItemResponsePagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(WorkspaceListItemResponseFromJSON)),
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
    };
}

export function WorkspaceListItemResponsePagedResponseToJSON(json: any): WorkspaceListItemResponsePagedResponse {
    return WorkspaceListItemResponsePagedResponseToJSONTyped(json, false);
}

export function WorkspaceListItemResponsePagedResponseToJSONTyped(value?: WorkspaceListItemResponsePagedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(WorkspaceListItemResponseToJSON)),
        'currentPage': value['currentPage'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'totalPages': value['totalPages'],
        'hasPreviousPage': value['hasPreviousPage'],
        'hasNextPage': value['hasNextPage'],
    };
}

