/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceItemDetailResponse } from './WorkspaceItemDetailResponse';
import {
    WorkspaceItemDetailResponseFromJSON,
    WorkspaceItemDetailResponseFromJSONTyped,
    WorkspaceItemDetailResponseToJSON,
    WorkspaceItemDetailResponseToJSONTyped,
} from './WorkspaceItemDetailResponse';

/**
 * ワークスペースアイテム操作レスポンス
 * @export
 * @interface WorkspaceItemResponse
 */
export interface WorkspaceItemResponse {
    /**
     * 成功フラグ
     * @type {boolean}
     * @memberof WorkspaceItemResponse
     */
    success?: boolean;
    /**
     * メッセージ
     * @type {string}
     * @memberof WorkspaceItemResponse
     */
    message?: string | null;
    /**
     * 
     * @type {WorkspaceItemDetailResponse}
     * @memberof WorkspaceItemResponse
     */
    workspaceItem?: WorkspaceItemDetailResponse;
}

/**
 * Check if a given object implements the WorkspaceItemResponse interface.
 */
export function instanceOfWorkspaceItemResponse(value: object): value is WorkspaceItemResponse {
    return true;
}

export function WorkspaceItemResponseFromJSON(json: any): WorkspaceItemResponse {
    return WorkspaceItemResponseFromJSONTyped(json, false);
}

export function WorkspaceItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'workspaceItem': json['workspaceItem'] == null ? undefined : WorkspaceItemDetailResponseFromJSON(json['workspaceItem']),
    };
}

export function WorkspaceItemResponseToJSON(json: any): WorkspaceItemResponse {
    return WorkspaceItemResponseToJSONTyped(json, false);
}

export function WorkspaceItemResponseToJSONTyped(value?: WorkspaceItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'workspaceItem': WorkspaceItemDetailResponseToJSON(value['workspaceItem']),
    };
}

