/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceUserDetailResponse } from './WorkspaceUserDetailResponse';
import {
    WorkspaceUserDetailResponseFromJSON,
    WorkspaceUserDetailResponseFromJSONTyped,
    WorkspaceUserDetailResponseToJSON,
    WorkspaceUserDetailResponseToJSONTyped,
} from './WorkspaceUserDetailResponse';

/**
 * ワークスペースユーザー登録レスポンス
 * @export
 * @interface WorkspaceUserResponse
 */
export interface WorkspaceUserResponse {
    /**
     * 成功フラグ
     * @type {boolean}
     * @memberof WorkspaceUserResponse
     */
    success?: boolean;
    /**
     * メッセージ
     * @type {string}
     * @memberof WorkspaceUserResponse
     */
    message?: string | null;
    /**
     * 
     * @type {WorkspaceUserDetailResponse}
     * @memberof WorkspaceUserResponse
     */
    workspaceUser?: WorkspaceUserDetailResponse;
}

/**
 * Check if a given object implements the WorkspaceUserResponse interface.
 */
export function instanceOfWorkspaceUserResponse(value: object): value is WorkspaceUserResponse {
    return true;
}

export function WorkspaceUserResponseFromJSON(json: any): WorkspaceUserResponse {
    return WorkspaceUserResponseFromJSONTyped(json, false);
}

export function WorkspaceUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'workspaceUser': json['workspaceUser'] == null ? undefined : WorkspaceUserDetailResponseFromJSON(json['workspaceUser']),
    };
}

export function WorkspaceUserResponseToJSON(json: any): WorkspaceUserResponse {
    return WorkspaceUserResponseToJSONTyped(json, false);
}

export function WorkspaceUserResponseToJSONTyped(value?: WorkspaceUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'workspaceUser': WorkspaceUserDetailResponseToJSON(value['workspaceUser']),
    };
}

