/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceItemRelationResponse } from './WorkspaceItemRelationResponse';
import {
    WorkspaceItemRelationResponseFromJSON,
    WorkspaceItemRelationResponseFromJSONTyped,
    WorkspaceItemRelationResponseToJSON,
    WorkspaceItemRelationResponseToJSONTyped,
} from './WorkspaceItemRelationResponse';

/**
 * ワークスペースアイテム関連一覧レスポンス
 * @export
 * @interface WorkspaceItemRelationsResponse
 */
export interface WorkspaceItemRelationsResponse {
    /**
     * 関連元としての関連一覧（このアイテムから他へ）
     * @type {Array<WorkspaceItemRelationResponse>}
     * @memberof WorkspaceItemRelationsResponse
     */
    relationsFrom?: Array<WorkspaceItemRelationResponse> | null;
    /**
     * 関連先としての関連一覧（他からこのアイテムへ）
     * @type {Array<WorkspaceItemRelationResponse>}
     * @memberof WorkspaceItemRelationsResponse
     */
    relationsTo?: Array<WorkspaceItemRelationResponse> | null;
    /**
     * 全関連数
     * @type {number}
     * @memberof WorkspaceItemRelationsResponse
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the WorkspaceItemRelationsResponse interface.
 */
export function instanceOfWorkspaceItemRelationsResponse(value: object): value is WorkspaceItemRelationsResponse {
    return true;
}

export function WorkspaceItemRelationsResponseFromJSON(json: any): WorkspaceItemRelationsResponse {
    return WorkspaceItemRelationsResponseFromJSONTyped(json, false);
}

export function WorkspaceItemRelationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceItemRelationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'relationsFrom': json['relationsFrom'] == null ? undefined : ((json['relationsFrom'] as Array<any>).map(WorkspaceItemRelationResponseFromJSON)),
        'relationsTo': json['relationsTo'] == null ? undefined : ((json['relationsTo'] as Array<any>).map(WorkspaceItemRelationResponseFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function WorkspaceItemRelationsResponseToJSON(json: any): WorkspaceItemRelationsResponse {
    return WorkspaceItemRelationsResponseToJSONTyped(json, false);
}

export function WorkspaceItemRelationsResponseToJSONTyped(value?: WorkspaceItemRelationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'relationsFrom': value['relationsFrom'] == null ? undefined : ((value['relationsFrom'] as Array<any>).map(WorkspaceItemRelationResponseToJSON)),
        'relationsTo': value['relationsTo'] == null ? undefined : ((value['relationsTo'] as Array<any>).map(WorkspaceItemRelationResponseToJSON)),
        'totalCount': value['totalCount'],
    };
}

