/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースユーザー詳細レスポンス
 * @export
 * @interface WorkspaceUserDetailResponse
 */
export interface WorkspaceUserDetailResponse {
    /**
     * ワークスペースID
     * @type {number}
     * @memberof WorkspaceUserDetailResponse
     */
    workspaceId?: number;
    /**
     * ユーザーID
     * @type {number}
     * @memberof WorkspaceUserDetailResponse
     */
    userId?: number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof WorkspaceUserDetailResponse
     */
    username?: string | null;
    /**
     * メールアドレス
     * @type {string}
     * @memberof WorkspaceUserDetailResponse
     */
    email?: string | null;
    /**
     * ワークスペース内での役割
     * @type {string}
     * @memberof WorkspaceUserDetailResponse
     */
    workspaceRole?: string | null;
    /**
     * 参加日時
     * @type {Date}
     * @memberof WorkspaceUserDetailResponse
     */
    joinedAt?: Date;
    /**
     * 最終アクセス日時
     * @type {Date}
     * @memberof WorkspaceUserDetailResponse
     */
    lastAccessedAt?: Date | null;
    /**
     * アクティブフラグ
     * @type {boolean}
     * @memberof WorkspaceUserDetailResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the WorkspaceUserDetailResponse interface.
 */
export function instanceOfWorkspaceUserDetailResponse(value: object): value is WorkspaceUserDetailResponse {
    return true;
}

export function WorkspaceUserDetailResponseFromJSON(json: any): WorkspaceUserDetailResponse {
    return WorkspaceUserDetailResponseFromJSONTyped(json, false);
}

export function WorkspaceUserDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceUserDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'workspaceRole': json['workspaceRole'] == null ? undefined : json['workspaceRole'],
        'joinedAt': json['joinedAt'] == null ? undefined : (new Date(json['joinedAt'])),
        'lastAccessedAt': json['lastAccessedAt'] == null ? undefined : (new Date(json['lastAccessedAt'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function WorkspaceUserDetailResponseToJSON(json: any): WorkspaceUserDetailResponse {
    return WorkspaceUserDetailResponseToJSONTyped(json, false);
}

export function WorkspaceUserDetailResponseToJSONTyped(value?: WorkspaceUserDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workspaceId': value['workspaceId'],
        'userId': value['userId'],
        'username': value['username'],
        'email': value['email'],
        'workspaceRole': value['workspaceRole'],
        'joinedAt': value['joinedAt'] == null ? value['joinedAt'] : value['joinedAt'].toISOString(),
        'lastAccessedAt': value['lastAccessedAt'] == null ? value['lastAccessedAt'] : value['lastAccessedAt'].toISOString(),
        'isActive': value['isActive'],
    };
}

