/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースリストアイテムレスポンス
 * @export
 * @interface WorkspaceListItemResponse
 */
export interface WorkspaceListItemResponse {
    /**
     * ワークスペースID
     * @type {number}
     * @memberof WorkspaceListItemResponse
     */
    id?: number;
    /**
     * ワークスペース名
     * @type {string}
     * @memberof WorkspaceListItemResponse
     */
    name: string | null;
    /**
     * ワークスペースコード
     * @type {string}
     * @memberof WorkspaceListItemResponse
     */
    code?: string | null;
    /**
     * ワークスペースの説明
     * @type {string}
     * @memberof WorkspaceListItemResponse
     */
    description?: string | null;
    /**
     * 組織ID
     * @type {number}
     * @memberof WorkspaceListItemResponse
     */
    organizationId?: number;
    /**
     * 組織名
     * @type {string}
     * @memberof WorkspaceListItemResponse
     */
    organizationName?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof WorkspaceListItemResponse
     */
    createdAt?: Date;
    /**
     * 更新日時
     * @type {Date}
     * @memberof WorkspaceListItemResponse
     */
    updatedAt?: Date | null;
    /**
     * アクティブフラグ
     * @type {boolean}
     * @memberof WorkspaceListItemResponse
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the WorkspaceListItemResponse interface.
 */
export function instanceOfWorkspaceListItemResponse(value: object): value is WorkspaceListItemResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WorkspaceListItemResponseFromJSON(json: any): WorkspaceListItemResponse {
    return WorkspaceListItemResponseFromJSONTyped(json, false);
}

export function WorkspaceListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'description': json['description'] == null ? undefined : json['description'],
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function WorkspaceListItemResponseToJSON(json: any): WorkspaceListItemResponse {
    return WorkspaceListItemResponseToJSONTyped(json, false);
}

export function WorkspaceListItemResponseToJSONTyped(value?: WorkspaceListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'description': value['description'],
        'organizationId': value['organizationId'],
        'organizationName': value['organizationName'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'isActive': value['isActive'],
    };
}

