/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ワークスペースアイテム関連情報レスポンス
 * @export
 * @interface WorkspaceItemRelationResponse
 */
export interface WorkspaceItemRelationResponse {
    /**
     * 関連ID
     * @type {number}
     * @memberof WorkspaceItemRelationResponse
     */
    id?: number;
    /**
     * 関連元アイテムID
     * @type {number}
     * @memberof WorkspaceItemRelationResponse
     */
    fromItemId?: number;
    /**
     * 関連元アイテムコード
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    fromItemCode?: string | null;
    /**
     * 関連元アイテム件名
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    fromItemSubject?: string | null;
    /**
     * 関連先アイテムID
     * @type {number}
     * @memberof WorkspaceItemRelationResponse
     */
    toItemId?: number;
    /**
     * 関連先アイテムコード
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    toItemCode?: string | null;
    /**
     * 関連先アイテム件名
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    toItemSubject?: string | null;
    /**
     * 関連タイプ
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    relationType?: string | null;
    /**
     * 作成日時
     * @type {Date}
     * @memberof WorkspaceItemRelationResponse
     */
    createdAt?: Date;
    /**
     * 作成者ID
     * @type {number}
     * @memberof WorkspaceItemRelationResponse
     */
    createdByUserId?: number;
    /**
     * 作成者ユーザー名
     * @type {string}
     * @memberof WorkspaceItemRelationResponse
     */
    createdByUsername?: string | null;
}

/**
 * Check if a given object implements the WorkspaceItemRelationResponse interface.
 */
export function instanceOfWorkspaceItemRelationResponse(value: object): value is WorkspaceItemRelationResponse {
    return true;
}

export function WorkspaceItemRelationResponseFromJSON(json: any): WorkspaceItemRelationResponse {
    return WorkspaceItemRelationResponseFromJSONTyped(json, false);
}

export function WorkspaceItemRelationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceItemRelationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fromItemId': json['fromItemId'] == null ? undefined : json['fromItemId'],
        'fromItemCode': json['fromItemCode'] == null ? undefined : json['fromItemCode'],
        'fromItemSubject': json['fromItemSubject'] == null ? undefined : json['fromItemSubject'],
        'toItemId': json['toItemId'] == null ? undefined : json['toItemId'],
        'toItemCode': json['toItemCode'] == null ? undefined : json['toItemCode'],
        'toItemSubject': json['toItemSubject'] == null ? undefined : json['toItemSubject'],
        'relationType': json['relationType'] == null ? undefined : json['relationType'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdByUserId': json['createdByUserId'] == null ? undefined : json['createdByUserId'],
        'createdByUsername': json['createdByUsername'] == null ? undefined : json['createdByUsername'],
    };
}

export function WorkspaceItemRelationResponseToJSON(json: any): WorkspaceItemRelationResponse {
    return WorkspaceItemRelationResponseToJSONTyped(json, false);
}

export function WorkspaceItemRelationResponseToJSONTyped(value?: WorkspaceItemRelationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fromItemId': value['fromItemId'],
        'fromItemCode': value['fromItemCode'],
        'fromItemSubject': value['fromItemSubject'],
        'toItemId': value['toItemId'],
        'toItemCode': value['toItemCode'],
        'toItemSubject': value['toItemSubject'],
        'relationType': value['relationType'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'createdByUserId': value['createdByUserId'],
        'createdByUsername': value['createdByUsername'],
    };
}

