/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { WorkspaceRole } from './WorkspaceRole';
/**
 * ワークスペースユーザー一覧用DTO（軽量）
 */
export type WorkspaceUserItem = {
    /**
     * ユーザーID
     */
    userId: number | string;
    /**
     * ユーザー名
     */
    username: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * アイデンティティアイコンURL（表示用）
     * AvatarTypeに応じて適切なURL（Gravatar/UserAvatar/AutoGenerated）が設定される
     */
    identityIconUrl: string;
    workspaceRole?: (null | WorkspaceRole);
    /**
     * アクティブフラグ
     */
    isActive?: boolean;
    /**
     * 最終ログイン日時
     */
    lastLoginAt?: string | null;
};

