/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { WorkspaceRole } from './WorkspaceRole';
/**
 * ワークスペースユーザー詳細レスポンス
 */
export type WorkspaceUserDetailResponse = {
    /**
     * ワークスペースID
     */
    workspaceId: number;
    /**
     * ユーザーID
     */
    userId: number;
    /**
     * ユーザー名
     */
    username: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * アイデンティティアイコンURL（表示用）
     * AvatarTypeに応じて適切なURL（Gravatar/UserAvatar/AutoGenerated）が設定される
     */
    identityIconUrl: string;
    workspaceRole?: (null | WorkspaceRole);
    /**
     * 参加日時
     */
    joinedAt?: string;
    /**
     * 最終アクセス日時
     */
    lastAccessedAt?: string | null;
    /**
     * アクティブフラグ
     */
    isActive?: boolean;
};

