/**
 * 絵文字リスト（軽量版）
 * フロントエンドの emoji-list.ts から抜粋
 * 主要な絵文字のみを含む
 */

export interface EmojiData {
  emoji: string;
  aliases: string[];
}

/**
 * 絵文字データのリスト
 * 必要に応じて追加可能
 */
export const emojiList: EmojiData[] = [
  // Smileys & Emotion
  { emoji: '😀', aliases: ['grinning'] },
  { emoji: '😃', aliases: ['smiley'] },
  { emoji: '😄', aliases: ['smile'] },
  { emoji: '😁', aliases: ['grin'] },
  { emoji: '😆', aliases: ['laughing', 'satisfied'] },
  { emoji: '😅', aliases: ['sweat_smile'] },
  { emoji: '🤣', aliases: ['rofl'] },
  { emoji: '😂', aliases: ['joy'] },
  { emoji: '🙂', aliases: ['slightly_smiling_face'] },
  { emoji: '🙃', aliases: ['upside_down_face'] },
  { emoji: '😉', aliases: ['wink'] },
  { emoji: '😊', aliases: ['blush'] },
  { emoji: '😇', aliases: ['innocent'] },
  { emoji: '🥰', aliases: ['smiling_face_with_three_hearts'] },
  { emoji: '😍', aliases: ['heart_eyes'] },
  { emoji: '🤩', aliases: ['star_struck'] },
  { emoji: '😘', aliases: ['kissing_heart'] },
  { emoji: '😋', aliases: ['yum'] },
  { emoji: '😜', aliases: ['stuck_out_tongue_winking_eye'] },
  { emoji: '😝', aliases: ['stuck_out_tongue_closed_eyes'] },
  { emoji: '🤑', aliases: ['money_mouth_face'] },
  { emoji: '🤗', aliases: ['hugs'] },
  { emoji: '🤭', aliases: ['hand_over_mouth'] },
  { emoji: '🤫', aliases: ['shushing_face'] },
  { emoji: '🤔', aliases: ['thinking'] },
  { emoji: '🤐', aliases: ['zipper_mouth_face'] },
  { emoji: '🤨', aliases: ['raised_eyebrow'] },
  { emoji: '😐', aliases: ['neutral_face'] },
  { emoji: '😑', aliases: ['expressionless'] },
  { emoji: '😶', aliases: ['no_mouth'] },
  { emoji: '😏', aliases: ['smirk'] },
  { emoji: '😒', aliases: ['unamused'] },
  { emoji: '🙄', aliases: ['roll_eyes'] },
  { emoji: '😬', aliases: ['grimacing'] },
  { emoji: '😮‍💨', aliases: ['face_exhaling'] },
  { emoji: '🤥', aliases: ['lying_face'] },
  { emoji: '😌', aliases: ['relieved'] },
  { emoji: '😔', aliases: ['pensive'] },
  { emoji: '😪', aliases: ['sleepy'] },
  { emoji: '🤤', aliases: ['drooling_face'] },
  { emoji: '😴', aliases: ['sleeping'] },
  { emoji: '😷', aliases: ['mask'] },
  { emoji: '🤒', aliases: ['face_with_thermometer'] },
  { emoji: '🤕', aliases: ['face_with_head_bandage'] },
  { emoji: '🤢', aliases: ['nauseated_face'] },
  { emoji: '🤮', aliases: ['vomiting_face'] },
  { emoji: '🤧', aliases: ['sneezing_face'] },
  { emoji: '🥵', aliases: ['hot_face'] },
  { emoji: '🥶', aliases: ['cold_face'] },
  { emoji: '🥴', aliases: ['woozy_face'] },
  { emoji: '😵', aliases: ['dizzy_face'] },
  { emoji: '🤯', aliases: ['exploding_head'] },
  { emoji: '🤠', aliases: ['cowboy_hat_face'] },
  { emoji: '🥳', aliases: ['partying_face'] },
  { emoji: '🥸', aliases: ['disguised_face'] },
  { emoji: '😎', aliases: ['sunglasses'] },
  { emoji: '🤓', aliases: ['nerd_face'] },
  { emoji: '🧐', aliases: ['monocle_face'] },
  { emoji: '😕', aliases: ['confused'] },
  { emoji: '😟', aliases: ['worried'] },
  { emoji: '🙁', aliases: ['slightly_frowning_face'] },
  { emoji: '☹️', aliases: ['frowning_face'] },
  { emoji: '😮', aliases: ['open_mouth'] },
  { emoji: '😯', aliases: ['hushed'] },
  { emoji: '😲', aliases: ['astonished'] },
  { emoji: '😳', aliases: ['flushed'] },
  { emoji: '🥺', aliases: ['pleading_face'] },
  { emoji: '😦', aliases: ['frowning'] },
  { emoji: '😧', aliases: ['anguished'] },
  { emoji: '😨', aliases: ['fearful'] },
  { emoji: '😰', aliases: ['cold_sweat'] },
  { emoji: '😥', aliases: ['disappointed_relieved'] },
  { emoji: '😢', aliases: ['cry'] },
  { emoji: '😭', aliases: ['sob'] },
  { emoji: '😱', aliases: ['scream'] },
  { emoji: '😖', aliases: ['confounded'] },
  { emoji: '😣', aliases: ['persevere'] },
  { emoji: '😞', aliases: ['disappointed'] },
  { emoji: '😓', aliases: ['sweat'] },
  { emoji: '😩', aliases: ['weary'] },
  { emoji: '😫', aliases: ['tired_face'] },
  { emoji: '🥱', aliases: ['yawning_face'] },
  { emoji: '😤', aliases: ['triumph'] },
  { emoji: '😡', aliases: ['rage', 'pout'] },
  { emoji: '😠', aliases: ['angry'] },
  { emoji: '🤬', aliases: ['cursing_face'] },
  { emoji: '😈', aliases: ['smiling_imp'] },
  { emoji: '👿', aliases: ['imp'] },
  { emoji: '💀', aliases: ['skull'] },
  { emoji: '☠️', aliases: ['skull_and_crossbones'] },
  // Gestures
  { emoji: '👋', aliases: ['wave'] },
  { emoji: '🤚', aliases: ['raised_back_of_hand'] },
  { emoji: '🖐️', aliases: ['raised_hand_with_fingers_splayed'] },
  { emoji: '✋', aliases: ['hand', 'raised_hand'] },
  { emoji: '🖖', aliases: ['vulcan_salute'] },
  { emoji: '👌', aliases: ['ok_hand'] },
  { emoji: '🤌', aliases: ['pinched_fingers'] },
  { emoji: '🤏', aliases: ['pinching_hand'] },
  { emoji: '✌️', aliases: ['v'] },
  { emoji: '🤞', aliases: ['crossed_fingers'] },
  { emoji: '🤟', aliases: ['love_you_gesture'] },
  { emoji: '🤘', aliases: ['metal'] },
  { emoji: '🤙', aliases: ['call_me_hand'] },
  { emoji: '👈', aliases: ['point_left'] },
  { emoji: '👉', aliases: ['point_right'] },
  { emoji: '👆', aliases: ['point_up_2'] },
  { emoji: '🖕', aliases: ['fu', 'middle_finger'] },
  { emoji: '👇', aliases: ['point_down'] },
  { emoji: '☝️', aliases: ['point_up'] },
  { emoji: '👍', aliases: ['+1', 'thumbsup'] },
  { emoji: '👎', aliases: ['-1', 'thumbsdown'] },
  { emoji: '✊', aliases: ['fist', 'fist_raised'] },
  { emoji: '👊', aliases: ['facepunch', 'punch', 'fist_oncoming'] },
  { emoji: '🤛', aliases: ['fist_left'] },
  { emoji: '🤜', aliases: ['fist_right'] },
  { emoji: '👏', aliases: ['clap'] },
  { emoji: '🙌', aliases: ['raised_hands'] },
  { emoji: '👐', aliases: ['open_hands'] },
  { emoji: '🤲', aliases: ['palms_up_together'] },
  { emoji: '🤝', aliases: ['handshake'] },
  { emoji: '🙏', aliases: ['pray'] },
  // Hearts
  { emoji: '❤️', aliases: ['heart'] },
  { emoji: '🧡', aliases: ['orange_heart'] },
  { emoji: '💛', aliases: ['yellow_heart'] },
  { emoji: '💚', aliases: ['green_heart'] },
  { emoji: '💙', aliases: ['blue_heart'] },
  { emoji: '💜', aliases: ['purple_heart'] },
  { emoji: '🖤', aliases: ['black_heart'] },
  { emoji: '🤍', aliases: ['white_heart'] },
  { emoji: '🤎', aliases: ['brown_heart'] },
  { emoji: '💔', aliases: ['broken_heart'] },
  { emoji: '💕', aliases: ['two_hearts'] },
  { emoji: '💞', aliases: ['revolving_hearts'] },
  { emoji: '💓', aliases: ['heartbeat'] },
  { emoji: '💗', aliases: ['heartpulse'] },
  { emoji: '💖', aliases: ['sparkling_heart'] },
  { emoji: '💘', aliases: ['cupid'] },
  { emoji: '💝', aliases: ['gift_heart'] },
  // Symbols
  { emoji: '✅', aliases: ['white_check_mark'] },
  { emoji: '❌', aliases: ['x'] },
  { emoji: '❓', aliases: ['question'] },
  { emoji: '❗', aliases: ['exclamation', 'heavy_exclamation_mark'] },
  { emoji: '⚠️', aliases: ['warning'] },
  { emoji: '🔴', aliases: ['red_circle'] },
  { emoji: '🟢', aliases: ['green_circle'] },
  { emoji: '🔵', aliases: ['blue_circle'] },
  { emoji: '⭐', aliases: ['star'] },
  { emoji: '🌟', aliases: ['star2'] },
  { emoji: '✨', aliases: ['sparkles'] },
  { emoji: '🎉', aliases: ['tada'] },
  { emoji: '🎊', aliases: ['confetti_ball'] },
  { emoji: '🔥', aliases: ['fire'] },
  { emoji: '💯', aliases: ['100'] },
  { emoji: '🚀', aliases: ['rocket'] },
  { emoji: '💡', aliases: ['bulb'] },
  { emoji: '📌', aliases: ['pushpin'] },
  { emoji: '📎', aliases: ['paperclip'] },
  { emoji: '🔗', aliases: ['link'] },
  { emoji: '📝', aliases: ['memo', 'pencil'] },
  { emoji: '📧', aliases: ['email', 'e-mail'] },
  { emoji: '📅', aliases: ['date'] },
  { emoji: '⏰', aliases: ['alarm_clock'] },
  { emoji: '⌛', aliases: ['hourglass'] },
  { emoji: '⏳', aliases: ['hourglass_flowing_sand'] },
];
