"use client";

import { useState } from "react";
import AppHeader from "@/components/common/AppHeader";
import type {
  UserResponse,
  MasterSkillResponse,
} from "@/connectors/api/pecus";
import {
  updateUserEmail,
  updateUserPassword,
  setUserSkills,
  updateProfile,
  uploadAvatarFile,
} from "@/actions/profile";
import {
  updateEmailFormSchema,
  updatePasswordFormSchema,
  updateSkillsFormSchema,
} from "@/schemas/profileSchemas";
import { useValidation } from "@/hooks/useValidation";

interface ProfileSettingsClientProps {
  initialUser: UserResponse;
  masterSkills: MasterSkillResponse[];
  fetchError?: string | null;
}

interface UserInfo {
  id: number;
  name?: string | null;
  email?: string | null;
  roles?: any[];
  isAdmin: boolean;
}

type TabType = "basic" | "skills" | "security" | "other";
type AlertType = "success" | "error" | "info";

interface AlertMessage {
  type: AlertType;
  message: string;
}

export default function ProfileSettingsClient({
  initialUser,
  masterSkills,
  fetchError,
}: ProfileSettingsClientProps) {
  const [activeTab, setActiveTab] = useState<TabType>("basic");
  const [user, setUser] = useState<UserResponse>(initialUser);
  const [alert, setAlert] = useState<AlertMessage | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const userInfo: UserInfo = {
    id: initialUser.id,
    name: initialUser.username,
    email: initialUser.email,
    isAdmin: initialUser.isAdmin || false,
  };

  // Basic Info
  const [username, setUsername] = useState<string>(user.username || "");
  const [newEmail, setNewEmail] = useState<string>(user.email || "");
  const [selectedAvatarType, setSelectedAvatarType] = useState<
    "Gravatar" | "UserAvatar" | "AutoGenerated"
  >(user.avatarType || "Gravatar");
  const [uploadedFileUrl, setUploadedFileUrl] = useState<string | null>(null);
  const [avatarPreviewUrl, setAvatarPreviewUrl] = useState<string | null>(null);
  const emailValidation = useValidation(updateEmailFormSchema);

  // Skills
  const [selectedSkillIds, setSelectedSkillIds] = useState<Set<number>>(
    new Set(user.skills?.map((s) => s.id) || [])
  );

  // Password
  const [currentPassword, setCurrentPassword] = useState<string>("");
  const [newPassword, setNewPassword] = useState<string>("");
  const [confirmPassword, setConfirmPassword] = useState<string>("");
  const [showPasswords, setShowPasswords] = useState<boolean>(false);
  const passwordValidation = useValidation(updatePasswordFormSchema);

  const handleEmailSubmit = async () => {
    if (emailValidation.hasErrors) {
      setAlert({
        type: "error",
        message: emailValidation.error || "メールアドレスが無効です",
      });
      return;
    }

    setIsLoading(true);
    try {
      const result = await updateUserEmail({ newEmail });
      if (result.success) {
        setAlert({
          type: "success",
          message: "メールアドレスが変更されました",
        });
        setNewEmail("");
      } else {
        setAlert({
          type: "error",
          message: result.message || "メール変更に失敗しました",
        });
      }
    } catch (error) {
      console.error("Email update error:", error);
      setAlert({
        type: "error",
        message: "予期しないエラーが発生しました",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleAvatarFileSelect = async (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const maxSize = 5 * 1024 * 1024;
    const allowedTypes = ["image/jpeg", "image/png", "image/webp", "image/gif"];

    if (file.size > maxSize) {
      setAlert({
        type: "error",
        message: "ファイルサイズは5MB以下である必要があります",
      });
      return;
    }

    if (!allowedTypes.includes(file.type)) {
      setAlert({
        type: "error",
        message:
          "JPEG、PNG、WebP、GIF形式のファイルのみアップロード可能です",
      });
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      setAvatarPreviewUrl(e.target?.result as string);
    };
    reader.readAsDataURL(file);

    setIsLoading(true);
    try {
      const formData = new FormData();
      formData.append("FileType", "Avatar");
      formData.append("ResourceId", user.id.toString());
      formData.append("File", file);

      const result = await uploadAvatarFile(formData);
      if (result.success && result.data.fileUrl) {
        setUploadedFileUrl(result.data.fileUrl);
        setAlert({
          type: "success",
          message: "ファイルがアップロードされました",
        });
      } else {
        setAlert({
          type: "error",
          message:
            (result as any).message || "ファイルアップロードに失敗しました",
        });
      }
    } catch (error) {
      console.error("Avatar upload error:", error);
      setAlert({
        type: "error",
        message: "ファイルアップロード中にエラーが発生しました",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleBasicInfoSubmit = async () => {
    setIsLoading(true);
    try {
      const result = await updateProfile({
        username: username !== user.username ? username : undefined,
        avatarType:
          selectedAvatarType !== user.avatarType
            ? selectedAvatarType
            : undefined,
        avatarUrl:
          uploadedFileUrl && selectedAvatarType === "UserAvatar"
            ? uploadedFileUrl
            : undefined,
        rowVersion: user.rowVersion,
      });

      if (result.success) {
        setUser(result.data);
        setUploadedFileUrl(null);
        setAvatarPreviewUrl(null);
        setAlert({
          type: "success",
          message: "基本情報が更新されました",
        });
      } else {
        setAlert({
          type: "error",
          message: result.message || "更新に失敗しました",
        });
      }
    } catch (error) {
      console.error("Profile update error:", error);
      setAlert({
        type: "error",
        message: "予期しないエラーが発生しました",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSkillToggle = (skillId: number) => {
    setSelectedSkillIds((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(skillId)) {
        newSet.delete(skillId);
      } else {
        newSet.add(skillId);
      }
      return newSet;
    });
  };

  const handleSkillsSubmit = async () => {
    setIsLoading(true);
    try {
      const result = await setUserSkills({
        skillIds: Array.from(selectedSkillIds),
      });

      if (result.success) {
        setAlert({
          type: "success",
          message: "スキルが更新されました",
        });
      } else {
        setAlert({
          type: "error",
          message: result.message || "スキル更新に失敗しました",
        });
      }
    } catch (error) {
      console.error("Skills update error:", error);
      setAlert({
        type: "error",
        message: "予期しないエラーが発生しました",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handlePasswordChange = async () => {
    const result = await passwordValidation.validate({
      currentPassword,
      newPassword,
      confirmPassword,
    });

    if (!result.success) {
      setAlert({
        type: "error",
        message: passwordValidation.error || "パスワードが無効です",
      });
      return;
    }

    setIsLoading(true);
    try {
      const updateResult = await updateUserPassword({
        currentPassword,
        newPassword,
        confirmPassword,
      });

      if (updateResult.success) {
        setAlert({
          type: "success",
          message: "パスワードが変更されました",
        });
        setCurrentPassword("");
        setNewPassword("");
        setConfirmPassword("");
      } else {
        setAlert({
          type: "error",
          message: updateResult.message || "パスワード変更に失敗しました",
        });
      }
    } catch (error) {
      console.error("Password update error:", error);
      setAlert({
        type: "error",
        message: "予期しないエラーが発生しました",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-screen">
      <AppHeader
        userInfo={userInfo}
        sidebarOpen={false}
        setSidebarOpen={() => {}}
        hideProfileMenu={true}
      />

      <main className="flex-1 p-6 bg-base-100">
          <div className="max-w-4xl mx-auto">
            <div className="mb-8">
              <h1 className="text-4xl font-bold mb-2">プロフィール設定</h1>
              <p className="text-base-content/70">
                ユーザー情報、スキル、パスワードを管理します
              </p>
            </div>

            {fetchError && (
              <div className="alert alert-error mb-6">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 shrink-0 stroke-current"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M10 14l-2-2m0 0l-2-2m2 2l2-2m-2 2l-2 2m0-4l2 2m0 0l2 2"
                  />
                </svg>
                <span>{fetchError}</span>
              </div>
            )}

            {alert && (
              <div className={`alert alert-${alert.type} mb-6`}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 shrink-0 stroke-current"
                  fill="none"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d={
                      alert.type === "success"
                        ? "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                        : "M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    }
                  />
                </svg>
                <span>{alert.message}</span>
                <button
                  type="button"
                  className="btn btn-sm btn-ghost"
                  onClick={() => setAlert(null)}
                >
                  ✕
                </button>
              </div>
            )}

            <div className="card bg-base-100 shadow-lg">
              <div className="tabs tab-bordered" role="tablist">
                <button
                  role="tab"
                  className={`tab ${activeTab === "basic" ? "tab-active" : ""}`}
                  onClick={() => setActiveTab("basic")}
                  type="button"
                >
                  基本情報
                </button>
                <button
                  role="tab"
                  className={`tab ${activeTab === "skills" ? "tab-active" : ""}`}
                  onClick={() => setActiveTab("skills")}
                  type="button"
                >
                  スキル
                </button>
                <button
                  role="tab"
                  className={`tab ${activeTab === "security" ? "tab-active" : ""}`}
                  onClick={() => setActiveTab("security")}
                  type="button"
                >
                  セキュリティ
                </button>
                <button
                  role="tab"
                  className={`tab ${activeTab === "other" ? "tab-active" : ""}`}
                  onClick={() => setActiveTab("other")}
                  type="button"
                >
                  その他の情報
                </button>
              </div>

              <div className="p-6">
                {activeTab === "basic" && (
                  <BasicInfoTab
                    user={user}
                    username={username}
                    newEmail={newEmail}
                    selectedAvatarType={selectedAvatarType}
                    avatarPreviewUrl={avatarPreviewUrl}
                    emailValidation={emailValidation}
                    isLoading={isLoading}
                    onUsernameChange={setUsername}
                    onEmailChange={async (email) => {
                      setNewEmail(email);
                      await emailValidation.validate({ newEmail: email });
                    }}
                    onEmailSubmit={handleEmailSubmit}
                    onAvatarTypeChange={setSelectedAvatarType}
                    onAvatarFileSelect={handleAvatarFileSelect}
                    onSubmit={handleBasicInfoSubmit}
                  />
                )}

                {activeTab === "skills" && (
                  <SkillsTab
                    masterSkills={masterSkills}
                    selectedSkillIds={selectedSkillIds}
                    isLoading={isLoading}
                    onSkillToggle={handleSkillToggle}
                    onSubmit={handleSkillsSubmit}
                  />
                )}

                {activeTab === "security" && (
                  <SecurityTab
                    currentPassword={currentPassword}
                    newPassword={newPassword}
                    confirmPassword={confirmPassword}
                    showPasswords={showPasswords}
                    passwordValidation={passwordValidation}
                    isLoading={isLoading}
                    onCurrentPasswordChange={setCurrentPassword}
                    onNewPasswordChange={setNewPassword}
                    onConfirmPasswordChange={setConfirmPassword}
                    onShowPasswordsToggle={() => setShowPasswords(!showPasswords)}
                    onSubmit={handlePasswordChange}
                  />
                )}

                {activeTab === "other" && <OtherTab user={user} />}
              </div>
            </div>
          </div>
        </main>
    </div>
  );
}

// Tab Components
interface BasicInfoTabProps {
  user: UserResponse;
  username: string;
  newEmail: string;
  selectedAvatarType: "Gravatar" | "UserAvatar" | "AutoGenerated";
  avatarPreviewUrl: string | null;
  emailValidation: any;
  isLoading: boolean;
  onUsernameChange: (value: string) => void;
  onEmailChange: (value: string) => Promise<void>;
  onEmailSubmit: () => void;
  onAvatarTypeChange: (value: "Gravatar" | "UserAvatar" | "AutoGenerated") => void;
  onAvatarFileSelect: (event: React.ChangeEvent<HTMLInputElement>) => void;
  onSubmit: () => void;
}

function BasicInfoTab({
  username,
  newEmail,
  selectedAvatarType,
  avatarPreviewUrl,
  emailValidation,
  isLoading,
  onUsernameChange,
  onEmailChange,
  onEmailSubmit,
  onAvatarTypeChange,
  onAvatarFileSelect,
  onSubmit,
}: BasicInfoTabProps) {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-semibold">基本情報</h2>

      <div className="form-control">
        <label htmlFor="username" className="label">
          <span className="label-text font-semibold">ユーザー名</span>
        </label>
        <input
          id="username"
          type="text"
          placeholder="ユーザー名を入力..."
          className="input input-bordered"
          value={username}
          onChange={(e) => onUsernameChange(e.target.value)}
          disabled={isLoading}
          maxLength={50}
        />
        <label className="label">
          <span className="label-text-alt">{username.length}/50</span>
        </label>
      </div>

      <div className="form-control">
        <label htmlFor="email" className="label">
          <span className="label-text font-semibold">メールアドレス</span>
        </label>
        <div className="flex gap-2">
          <input
            id="email"
            type="email"
            placeholder="新しいメールアドレスを入力..."
            className={`input input-bordered flex-1 ${
              emailValidation.hasErrors ? "input-error" : ""
            }`}
            value={newEmail}
            onChange={(e) => onEmailChange(e.target.value)}
            disabled={isLoading}
            maxLength={100}
          />
          <button
            type="button"
            className="btn btn-primary"
            onClick={onEmailSubmit}
            disabled={isLoading || emailValidation.hasErrors || !newEmail}
          >
            {isLoading ? (
              <span className="loading loading-spinner loading-sm"></span>
            ) : (
              "変更"
            )}
          </button>
        </div>
        {emailValidation.error && (
          <label className="label">
            <span className="label-text-alt text-error">
              {emailValidation.error}
            </span>
          </label>
        )}
      </div>

      <div className="divider">アバター設定</div>

      <div className="form-control">
        <label className="label">
          <span className="label-text font-semibold">アバタータイプ</span>
        </label>
        <div className="space-y-2">
          {(["Gravatar", "UserAvatar", "AutoGenerated"] as const).map(
            (type) => (
              <label key={type} className="label cursor-pointer">
                <span className="label-text">{type}</span>
                <input
                  type="radio"
                  name="avatarType"
                  className="radio"
                  value={type}
                  checked={selectedAvatarType === type}
                  onChange={() => onAvatarTypeChange(type)}
                  disabled={isLoading}
                />
              </label>
            )
          )}
        </div>
      </div>

      {selectedAvatarType === "UserAvatar" && (
        <div className="form-control">
          <label htmlFor="avatar-file" className="label">
            <span className="label-text font-semibold">アバター画像</span>
          </label>
          <input
            id="avatar-file"
            type="file"
            accept="image/jpeg,image/png,image/webp,image/gif"
            className="file-input file-input-bordered"
            onChange={onAvatarFileSelect}
            disabled={isLoading}
          />
          <label className="label">
            <span className="label-text-alt">最大 5MB、JPEG/PNG/WebP/GIF</span>
          </label>

          {avatarPreviewUrl && (
            <div className="mt-4">
              <p className="text-sm font-semibold mb-2">プレビュー:</p>
              <img
                src={avatarPreviewUrl}
                alt="Avatar preview"
                className="w-24 h-24 rounded-lg object-cover"
              />
            </div>
          )}
        </div>
      )}

      <div className="flex gap-2 pt-4">
        <button
          type="button"
          className="btn btn-primary flex-1"
          onClick={onSubmit}
          disabled={isLoading}
        >
          {isLoading ? (
            <>
              <span className="loading loading-spinner loading-sm"></span>
              保存中...
            </>
          ) : (
            "保存"
          )}
        </button>
      </div>
    </div>
  );
}

interface SkillsTabProps {
  masterSkills: MasterSkillResponse[];
  selectedSkillIds: Set<number>;
  isLoading: boolean;
  onSkillToggle: (skillId: number) => void;
  onSubmit: () => void;
}

function SkillsTab({
  masterSkills,
  selectedSkillIds,
  isLoading,
  onSkillToggle,
  onSubmit,
}: SkillsTabProps) {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-semibold">スキル</h2>

      <div className="form-control">
        <label className="label">
          <span className="label-text font-semibold text-base">スキル選択</span>
          <span className="label-text-alt">
            {selectedSkillIds.size} / {masterSkills.length} 個選択中
          </span>
        </label>

        <details className="dropdown w-full">
          <summary className="btn btn-outline w-full justify-start">
            {selectedSkillIds.size > 0
              ? `${selectedSkillIds.size} 個のスキルを選択中`
              : "スキルを選択してください"}
          </summary>
          <ul className="dropdown-content menu bg-base-100 rounded-box w-full p-2 shadow-lg border border-base-300 max-h-60 overflow-y-auto z-[1]">
            {masterSkills.length === 0 ? (
              <li className="text-center text-base-content/60 py-4">
                利用可能なスキルがありません
              </li>
            ) : (
              masterSkills.map((skill) => (
                <li key={skill.id}>
                  <label className="label cursor-pointer gap-3 hover:bg-base-200 rounded p-2">
                    <input
                      type="checkbox"
                      checked={selectedSkillIds.has(skill.id)}
                      onChange={() => onSkillToggle(skill.id)}
                      className="checkbox checkbox-primary checkbox-sm"
                      disabled={isLoading}
                    />
                    <span className="label-text flex-1 flex flex-col">
                      <span className="font-semibold">{skill.name}</span>
                      {skill.description && (
                        <span className="text-xs text-base-content/60">
                          {skill.description}
                        </span>
                      )}
                    </span>
                  </label>
                </li>
              ))
            )}
          </ul>
        </details>

        {selectedSkillIds.size > 0 && (
          <div className="flex flex-wrap gap-2 mt-4">
            {Array.from(selectedSkillIds).map((skillId) => {
              const skill = masterSkills.find((s) => s.id === skillId);
              return (
                <div key={skillId} className="badge badge-primary gap-2">
                  {skill?.name || `スキルID: ${skillId}`}
                  <button
                    type="button"
                    onClick={() => onSkillToggle(skillId)}
                    className="btn btn-ghost btn-xs no-animation"
                    aria-label={`${skill?.name}を削除`}
                    disabled={isLoading}
                  >
                    ✕
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </div>

      <div className="flex gap-2 pt-4">
        <button
          type="button"
          className="btn btn-primary flex-1"
          onClick={onSubmit}
          disabled={isLoading}
        >
          {isLoading ? (
            <>
              <span className="loading loading-spinner loading-sm"></span>
              保存中...
            </>
          ) : (
            "保存"
          )}
        </button>
      </div>
    </div>
  );
}

interface SecurityTabProps {
  currentPassword: string;
  newPassword: string;
  confirmPassword: string;
  showPasswords: boolean;
  passwordValidation: any;
  isLoading: boolean;
  onCurrentPasswordChange: (value: string) => void;
  onNewPasswordChange: (value: string) => void;
  onConfirmPasswordChange: (value: string) => void;
  onShowPasswordsToggle: () => void;
  onSubmit: () => void;
}

function SecurityTab({
  currentPassword,
  newPassword,
  confirmPassword,
  showPasswords,
  passwordValidation,
  isLoading,
  onCurrentPasswordChange,
  onNewPasswordChange,
  onConfirmPasswordChange,
  onShowPasswordsToggle,
  onSubmit,
}: SecurityTabProps) {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-semibold">セキュリティ</h2>

      <div className="alert alert-warning">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          className="h-6 w-6 shrink-0 stroke-current"
          fill="none"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            d="M12 9v2m0 4v2m0 0a9 9 0 11-9-9 9 9 0 019 9z"
          />
        </svg>
        <span>
          パスワードは大文字・小文字・数字を含む8文字以上である必要があります
        </span>
      </div>

      <div className="form-control">
        <label htmlFor="current-password" className="label">
          <span className="label-text font-semibold">現在のパスワード</span>
        </label>
        <input
          id="current-password"
          type={showPasswords ? "text" : "password"}
          placeholder="現在のパスワードを入力..."
          className="input input-bordered"
          value={currentPassword}
          onChange={(e) => onCurrentPasswordChange(e.target.value)}
          disabled={isLoading}
        />
      </div>

      <div className="form-control">
        <label htmlFor="new-password" className="label">
          <span className="label-text font-semibold">新しいパスワード</span>
        </label>
        <input
          id="new-password"
          type={showPasswords ? "text" : "password"}
          placeholder="新しいパスワードを入力..."
          className={`input input-bordered ${
            newPassword && passwordValidation.hasErrors ? "input-error" : ""
          }`}
          value={newPassword}
          onChange={(e) => onNewPasswordChange(e.target.value)}
          disabled={isLoading}
        />
      </div>

      <div className="form-control">
        <label htmlFor="confirm-password" className="label">
          <span className="label-text font-semibold">
            新しいパスワード（確認）
          </span>
        </label>
        <input
          id="confirm-password"
          type={showPasswords ? "text" : "password"}
          placeholder="新しいパスワードを再度入力..."
          className={`input input-bordered ${
            confirmPassword && passwordValidation.hasErrors
              ? "input-error"
              : ""
          }`}
          value={confirmPassword}
          onChange={(e) => onConfirmPasswordChange(e.target.value)}
          disabled={isLoading}
        />
      </div>

      <label className="label cursor-pointer">
        <span className="label-text">パスワードを表示</span>
        <input
          type="checkbox"
          className="checkbox"
          checked={showPasswords}
          onChange={onShowPasswordsToggle}
          disabled={isLoading}
        />
      </label>

      {passwordValidation.error && (
        <div className="alert alert-error">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M10 14l-2-2m0 0l-2-2m2 2l2-2m-2 2l-2 2"
            />
          </svg>
          <span>{passwordValidation.error}</span>
        </div>
      )}

      <div className="flex gap-2 pt-4">
        <button
          type="button"
          className="btn btn-primary flex-1"
          onClick={onSubmit}
          disabled={
            isLoading ||
            !currentPassword ||
            !newPassword ||
            !confirmPassword ||
            passwordValidation.hasErrors
          }
        >
          {isLoading ? (
            <>
              <span className="loading loading-spinner loading-sm"></span>
              変更中...
            </>
          ) : (
            "パスワードを変更"
          )}
        </button>
      </div>
    </div>
  );
}

interface OtherTabProps {
  user: UserResponse;
}

function OtherTab({ user }: OtherTabProps) {
  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-semibold">その他の情報</h2>

      {user.identityIconUrl && (
        <div className="form-control">
          <label className="label">
            <span className="label-text font-semibold">
              アイデンティティアイコン
            </span>
          </label>
          <div className="flex items-center gap-4">
            <img
              src={user.identityIconUrl}
              alt="Identity icon"
              className="w-16 h-16 rounded-lg"
            />
            <p className="text-sm text-base-content/70">
              自動生成されたアイデンティティアイコンです
            </p>
          </div>
        </div>
      )}

      <div className="form-control">
        <label className="label">
          <span className="label-text font-semibold">ユーザー ID</span>
        </label>
        <input
          type="text"
          className="input input-bordered"
          value={user.loginId}
          disabled
        />
      </div>

      <div className="form-control">
        <label className="label">
          <span className="label-text font-semibold">アカウント作成日</span>
        </label>
        <input
          type="text"
          className="input input-bordered"
          value={user.createdAt ? new Date(user.createdAt).toLocaleString("ja-JP") : ""}
          disabled
        />
      </div>

      <div className="form-control">
        <label className="label">
          <span className="label-text font-semibold">管理者権限</span>
        </label>
        <input
          type="text"
          className="input input-bordered"
          value={user.isAdmin ? "あり" : "なし"}
          disabled
        />
      </div>
    </div>
  );
}
