using Microsoft.EntityFrameworkCore;
using Pecus.Exceptions;
using Pecus.Libs.AI;
using Pecus.Libs.DB;
using Pecus.Libs.DB.Models;
using Pecus.Libs.DB.Models.Enums;
using Pecus.Libs.Utils;

namespace Pecus.Services;

/// <summary>
/// 組織管理サービス
/// </summary>
public class OrganizationService
{
    private readonly ApplicationDbContext _context;
    private readonly UserService _userService;

    public OrganizationService(ApplicationDbContext context, UserService userService)
    {
        _context = context;
        _userService = userService;
    }

    /// <summary>
    /// 組織を作成（管理者ユーザーも同時作成）
    /// </summary>
    /// <remarks>
    /// 組織と管理者ユーザーを作成します。
    /// 管理者ユーザーのパスワードはリクエストから取得せず、パスワード設定トークンを生成します。
    /// トークンはメール送信で使用されます。
    /// </remarks>
    public async Task<(Organization organization, User adminUser, string passwordSetupToken, DateTime tokenExpiresAt)> CreateOrganizationWithUserAsync(
        CreateOrganizationRequest request
    )
    {
        using var transaction = await _context.Database.BeginTransactionAsync();
        try
        {
            // 組織コードの重複チェック
            if (
                !string.IsNullOrEmpty(request.Code)
                && await _context.Organizations.AnyAsync(o => o.Code == request.Code)
            )
            {
                throw new DuplicateException("組織コードは既に使用されています。");
            }

            // 管理者メールアドレスの重複チェック
            if (await _context.Users.AnyAsync(u => u.Email == request.AdminEmail))
            {
                throw new DuplicateException("管理者メールアドレスは既に使用されています。");
            }

            // 組織を作成
            var organization = new Organization
            {
                Name = request.Name,
                Code = request.Code,
                Description = request.Description,
                RepresentativeName = request.RepresentativeName,
                PhoneNumber = request.PhoneNumber,
                Email = request.Email,
                CreatedAt = DateTime.UtcNow,
                CreatedByUserId = null,
                IsActive = true,
            };

            _context.Organizations.Add(organization);
            await _context.SaveChangesAsync();

            // 組織設定を作成（初期値はFreeプラン）
            var setting = new OrganizationSetting
            {
                OrganizationId = organization.Id,
                TaskOverdueThreshold = 0,
                WeeklyReportDeliveryDay = 0,
                MailFromAddress = organization.Email,
                MailFromName = organization.Name,
                GenerativeApiVendor = GenerativeApiVendor.None,
                GenerativeApiKey = null,
                Plan = OrganizationPlan.Free,
                GamificationEnabled = true,
                GamificationAllowUserOverride = true,
                GamificationBadgeVisibility = BadgeVisibility.Workspace,
                UpdatedAt = DateTimeOffset.UtcNow,
                UpdatedByUserId = null,
            };
            _context.OrganizationSettings.Add(setting);
            await _context.SaveChangesAsync();
            organization.Setting = setting;

            // ユニークなLoginIdを生成
            var loginId = await CodeGenerator.GenerateUniqueLoginIdAsync(_context);

            // 管理者ユーザーを作成（パスワード未設定）
            var adminUser = new User
            {
                Username = request.AdminUsername,
                Email = request.AdminEmail,
                LoginId = loginId,
                PasswordHash = string.Empty,
                AvatarType = AvatarType.AutoGenerated,
                IsActive = true,
                CreatedAt = DateTime.UtcNow,
                OrganizationId = organization.Id,
            };

            _context.Users.Add(adminUser);
            await _context.SaveChangesAsync();

            // ユーザー設定を作成（初期値）
            var adminUserSetting = new UserSetting
            {
                UserId = adminUser.Id,
                CanReceiveEmail = true,
                CanReceiveRealtimeNotification = true,
                BadgeVisibility = null,
                UpdatedAt = DateTimeOffset.UtcNow,
                UpdatedByUserId = null,
            };
            _context.UserSettings.Add(adminUserSetting);
            await _context.SaveChangesAsync();

            // パスワード設定トークンを生成
            var token = GeneratePasswordResetToken();
            var tokenExpiresAt = DateTime.UtcNow.AddHours(24); // 24時間有効

            // 管理者ユーザーに設定（パスワードは未設定状態にする）
            adminUser.PasswordHash = string.Empty; // パスワード未設定
            adminUser.PasswordResetToken = token;
            adminUser.PasswordResetTokenExpiresAt = tokenExpiresAt;

            // Admin ロールを取得
            var adminRole = await _context.Roles.FirstOrDefaultAsync(r => r.Name == SystemRole.Admin);
            if (adminRole != null)
            {
                adminUser.Roles.Add(adminRole);
            }

            // 組織の作成者を管理者ユーザーに設定
            organization.CreatedByUserId = adminUser.Id;

            await _context.SaveChangesAsync();

            // 管理者ユーザーに対応する ChatActor を作成
            var adminChatActor = new ChatActor
            {
                OrganizationId = organization.Id,
                ActorType = ChatActorType.User,
                UserId = adminUser.Id,
                DisplayName = adminUser.Username,
                AvatarType = adminUser.AvatarType,
                AvatarUrl = adminUser.UserAvatarPath,
            };
            _context.ChatActors.Add(adminChatActor);
            await _context.SaveChangesAsync();

            // Chat ボットを作成
            var chatBot = new Bot
            {
                OrganizationId = organization.Id,
                Type = BotType.ChatBot,
                Name = "Coati Bot",
                IconUrl = "/icons/bot/chat.webp",
                Persona = BotPersonaHelper.GetChatBotPersona(),
            };
            _context.Bots.Add(chatBot);
            await _context.SaveChangesAsync();

            // Chat ボット用 ChatActor を作成
            var chatBotActor = new ChatActor
            {
                OrganizationId = organization.Id,
                ActorType = ChatActorType.Bot,
                BotId = chatBot.Id,
                DisplayName = chatBot.Name,
                AvatarUrl = chatBot.IconUrl,
            };
            _context.ChatActors.Add(chatBotActor);

            // System ボットを作成
            var systemBot = new Bot
            {
                OrganizationId = organization.Id,
                Type = BotType.SystemBot,
                Name = "Butler Bot",
                IconUrl = "/icons/bot/system.webp",
                Persona = BotPersonaHelper.GetSystemBotPersona(),
            };
            _context.Bots.Add(systemBot);
            await _context.SaveChangesAsync();

            // System ボット用 ChatActor を作成
            var systemBotActor = new ChatActor
            {
                OrganizationId = organization.Id,
                ActorType = ChatActorType.Bot,
                BotId = systemBot.Id,
                DisplayName = systemBot.Name,
                AvatarUrl = systemBot.IconUrl,
            };
            _context.ChatActors.Add(systemBotActor);
            await _context.SaveChangesAsync();

            // グループチャットルームを作成（管理者 + Coati Bot）
            var groupRoom = new ChatRoom
            {
                Type = ChatRoomType.Group,
                Name = "グループチャット",
                OrganizationId = organization.Id,
                CreatedByUserId = adminUser.Id,
                Members = new List<ChatRoomMember>
                {
                    new() { ChatActorId = adminChatActor.Id, Role = ChatRoomRole.Owner },
                    new() { ChatActorId = chatBotActor.Id, Role = ChatRoomRole.Member },
                },
            };
            _context.ChatRooms.Add(groupRoom);

            // システム通知ルームを作成（管理者 + System Bot）
            var systemRoom = new ChatRoom
            {
                Type = ChatRoomType.System,
                Name = "システム通知",
                OrganizationId = organization.Id,
                CreatedByUserId = adminUser.Id,
                Members = new List<ChatRoomMember>
                {
                    new() { ChatActorId = adminChatActor.Id, Role = ChatRoomRole.Owner },
                    new() { ChatActorId = systemBotActor.Id, Role = ChatRoomRole.Member },
                },
            };
            _context.ChatRooms.Add(systemRoom);

            await _context.SaveChangesAsync();

            await transaction.CommitAsync();
            return (organization, adminUser, token, tokenExpiresAt);
        }
        catch
        {
            await transaction.RollbackAsync();
            throw;
        }
    }

    /// <summary>
    /// パスワード設定トークンを生成（URL安全なBase64）
    /// </summary>
    public static string GeneratePasswordResetToken()
    {
        using var rng = System.Security.Cryptography.RandomNumberGenerator.Create();
        var tokenBytes = new byte[32];
        rng.GetBytes(tokenBytes);
        // URL安全なBase64エンコード（+を-に、/を_に置換し、=パディングを削除）
        return Convert.ToBase64String(tokenBytes)
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');
    }

    /// <summary>
    /// 変更を保存
    /// </summary>
    public async Task SaveChangesAsync() => await _context.SaveChangesAsync();

    /// <summary>
    /// 組織IDで取得
    /// </summary>
    public async Task<Organization?> GetOrganizationByIdAsync(int organizationId) =>
        await _context
            .Organizations
            .Include(o => o.Users)
            .Include(o => o.Setting)
            .FirstOrDefaultAsync(o => o.Id == organizationId);

    /// <summary>
    /// 組織コードで取得
    /// </summary>
    public async Task<Organization?> GetOrganizationByCodeAsync(string code) =>
        await _context
            .Organizations
            .Include(o => o.Users)
            .Include(o => o.Setting)
            .FirstOrDefaultAsync(o => o.Code == code);

    /// <summary>
    /// 組織をページネーション付きで取得
    /// </summary>
    public async Task<(
        List<Organization> organizations,
        int totalCount
    )> GetOrganizationsPagedAsync(int page, int pageSize, bool? activeOnly = null)
    {
        var query = _context
            .Organizations
            .Include(o => o.Users)
            .Include(o => o.Setting)
            .AsQueryable();

        if (activeOnly == true)
        {
            query = query.Where(o => o.IsActive);
        }

        query = query.OrderBy(o => o.Id);

        var totalCount = await query.CountAsync();
        var organizations = await query
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .AsSplitQuery()
            .ToListAsync();

        return (organizations, totalCount);
    }

    /// <summary>
    /// 組織を更新（管理者用）
    /// </summary>
    public async Task<Organization> AdminUpdateOrganizationAsync(
        int organizationId,
        AdminUpdateOrganizationRequest request,
        int? updatedByUserId = null
    )
    {
        var organization = await _context.Organizations.FindAsync(organizationId);
        if (organization == null)
        {
            throw new NotFoundException("組織が見つかりません。");
        }

        if (request.Name != null)
        {
            organization.Name = request.Name;
        }

        if (request.Description != null)
        {
            organization.Description = request.Description;
        }

        if (request.RepresentativeName != null)
        {
            organization.RepresentativeName = request.RepresentativeName;
        }

        if (request.PhoneNumber != null)
        {
            organization.PhoneNumber = request.PhoneNumber;
        }

        if (request.Email != null)
        {
            organization.Email = request.Email;
        }

        organization.UpdatedAt = DateTime.UtcNow;
        organization.UpdatedByUserId = updatedByUserId;

        // OriginalValue に設定することで WHERE 句に RowVersion 条件が追加される
        _context.Entry(organization).Property(e => e.RowVersion).OriginalValue = request.RowVersion;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            await RaiseConflictException(organizationId);
        }

        return organization;
    }

    /// <summary>
    /// 組織設定を更新（管理者用）
    /// </summary>
    public async Task<OrganizationSettingResponse> AdminUpdateOrganizationSettingAsync(
        int organizationId,
        AdminUpdateOrganizationSettingRequest request,
        int? updatedByUserId = null
    )
    {
        var organization = await _context.Organizations.FindAsync(organizationId);
        if (organization == null)
        {
            throw new NotFoundException("組織が見つかりません。");
        }

        var setting = await _context.OrganizationSettings.FirstOrDefaultAsync(s => s.OrganizationId == organizationId);
        if (setting == null)
        {
            throw new NotFoundException("組織設定が見つかりません。");
        }

        // 楽観的ロックチェック
        if (setting.RowVersion != request.RowVersion)
        {
            await RaiseConflictException(organizationId);
        }

        // 生成APIベンダーが指定されている場合は API キー必須
        if (request.GenerativeApiVendor != GenerativeApiVendor.None && string.IsNullOrWhiteSpace(request.GenerativeApiKey))
        {
            throw new InvalidOperationException("生成APIベンダーを利用する場合、APIキーは必須です。");
        }

        var normalizedApiKey = request.GenerativeApiVendor == GenerativeApiVendor.None
            ? null
            : request.GenerativeApiKey?.Trim();

        setting.TaskOverdueThreshold = request.TaskOverdueThreshold;
        setting.WeeklyReportDeliveryDay = request.WeeklyReportDeliveryDay;
        setting.MailFromAddress = request.MailFromAddress;
        setting.MailFromName = request.MailFromName;
        setting.GenerativeApiVendor = request.GenerativeApiVendor;
        setting.GenerativeApiKey = normalizedApiKey;
        setting.GenerativeApiModel = request.GenerativeApiVendor == GenerativeApiVendor.None
            ? null
            : request.GenerativeApiModel;
        setting.Plan = request.Plan;
        setting.HelpNotificationTarget = request.HelpNotificationTarget;
        setting.RequireEstimateOnTaskCreation = request.RequireEstimateOnTaskCreation;
        setting.EnforcePredecessorCompletion = request.EnforcePredecessorCompletion;
        setting.DashboardHelpCommentMaxCount = request.DashboardHelpCommentMaxCount;
        setting.GroupChatScope = request.GroupChatScope;
        setting.DefaultWorkspaceMode = request.DefaultWorkspaceMode;
        setting.GamificationEnabled = request.GamificationEnabled;
        setting.GamificationBadgeVisibility = request.GamificationBadgeVisibility ?? BadgeVisibility.Private;
        setting.GamificationAllowUserOverride = request.GamificationAllowUserOverride;
        setting.BotGroupChatMessagesEnabled = request.BotGroupChatMessagesEnabled;
        setting.UpdatedAt = DateTimeOffset.UtcNow;
        setting.UpdatedByUserId = updatedByUserId;

        // OriginalValue に設定することで WHERE 句に RowVersion 条件が追加される
        _context.Entry(setting).Property(e => e.RowVersion).OriginalValue = request.RowVersion;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            await RaiseConflictException(organizationId);
        }

        return new OrganizationSettingResponse
        {
            TaskOverdueThreshold = setting.TaskOverdueThreshold,
            WeeklyReportDeliveryDay = setting.WeeklyReportDeliveryDay,
            MailFromAddress = setting.MailFromAddress,
            MailFromName = setting.MailFromName,
            GenerativeApiVendor = setting.GenerativeApiVendor,
            GenerativeApiKey = setting.GenerativeApiKey,
            GenerativeApiModel = setting.GenerativeApiModel,
            Plan = setting.Plan,
            HelpNotificationTarget = setting.HelpNotificationTarget,
            RequireEstimateOnTaskCreation = setting.RequireEstimateOnTaskCreation,
            EnforcePredecessorCompletion = setting.EnforcePredecessorCompletion,
            DashboardHelpCommentMaxCount = setting.DashboardHelpCommentMaxCount,
            GroupChatScope = setting.GroupChatScope,
            DefaultWorkspaceMode = setting.DefaultWorkspaceMode,
            GamificationEnabled = setting.GamificationEnabled,
            GamificationBadgeVisibility = setting.GamificationBadgeVisibility,
            GamificationAllowUserOverride = setting.GamificationAllowUserOverride,
            BotGroupChatMessagesEnabled = setting.BotGroupChatMessagesEnabled,
            RowVersion = setting.RowVersion,
        };
    }
    public async Task<Organization> BackendUpdateOrganizationAsync(
        int organizationId,
        BackendUpdateOrganizationRequest request,
        int? updatedByUserId = null
    )
    {
        var organization = await _context.Organizations.FindAsync(organizationId);
        if (organization == null)
        {
            throw new NotFoundException("組織が見つかりません。");
        }

        // 組織コードの重複チェック（自分以外）
        if (!string.IsNullOrEmpty(request.Code) && request.Code != organization.Code)
        {
            if (
                await _context.Organizations.AnyAsync(o =>
                    o.Code == request.Code && o.Id != organizationId
                )
            )
            {
                throw new DuplicateException("組織コードは既に使用されています。");
            }
        }

        if (request.Name != null)
        {
            organization.Name = request.Name;
        }

        if (request.Code != null)
        {
            organization.Code = request.Code;
        }

        if (request.Description != null)
        {
            organization.Description = request.Description;
        }

        if (request.RepresentativeName != null)
        {
            organization.RepresentativeName = request.RepresentativeName;
        }

        if (request.PhoneNumber != null)
        {
            organization.PhoneNumber = request.PhoneNumber;
        }

        if (request.Email != null)
        {
            organization.Email = request.Email;
        }

        if (request.IsActive.HasValue)
        {
            organization.IsActive = request.IsActive.Value;
        }

        organization.UpdatedAt = DateTime.UtcNow;
        organization.UpdatedByUserId = updatedByUserId;

        // OriginalValue に設定することで WHERE 句に RowVersion 条件が追加される
        _context.Entry(organization).Property(e => e.RowVersion).OriginalValue = request.RowVersion;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            await RaiseConflictException(organizationId);
        }

        return organization;
    }

    /// <summary>
    /// 組織のアクティブ状態を設定
    /// </summary>
    public async Task<bool> SetOrganizationActiveStatusAsync(
        int organizationId,
        SetOrganizationActiveStatusRequest request,
        int? updatedByUserId = null
    )
    {
        var organization = await _context.Organizations.FindAsync(organizationId);
        if (organization == null)
        {
            return false;
        }

        // 楽観的ロック：RowVersion を検証
        organization.IsActive = request.IsActive;
        organization.UpdatedAt = DateTime.UtcNow;
        organization.UpdatedByUserId = updatedByUserId;

        // OriginalValue に設定することで WHERE 句に RowVersion 条件が追加される
        _context.Entry(organization).Property(e => e.RowVersion).OriginalValue = request.RowVersion;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            await RaiseConflictException(organizationId);
        }

        return true;
    }

    /// <summary>
    /// 組織の所属ユーザーを取得
    /// </summary>
    public async Task<List<User>> GetOrganizationUsersAsync(int organizationId) =>
        await _context
            .Users.Include(u => u.Roles)
            .Where(u => u.OrganizationId == organizationId)
            .ToListAsync();


    private async Task RaiseConflictException(int organizationId)
    {
        var latestOrganization = await _context.Organizations
            .Include(o => o.Users)
            .Include(o => o.Setting)
            .FirstOrDefaultAsync(o => o.Id == organizationId);
        if (latestOrganization == null)
        {
            throw new NotFoundException("組織が見つかりません。");
        }
        throw new ConcurrencyException<OrganizationResponse>(
            "別のユーザーが同時に変更しました。ページをリロードして再度操作してください。",
            new OrganizationResponse
            {
                Id = latestOrganization.Id,
                Name = latestOrganization.Name,
                Code = latestOrganization.Code,
                Description = latestOrganization.Description,
                RepresentativeName = latestOrganization.RepresentativeName,
                PhoneNumber = latestOrganization.PhoneNumber,
                Email = latestOrganization.Email,
                CreatedAt = latestOrganization.CreatedAt,
                UpdatedAt = latestOrganization.UpdatedAt,
                IsActive = latestOrganization.IsActive,
                UserCount = latestOrganization.Users.Count,
                RowVersion = latestOrganization.RowVersion!,
                Setting = latestOrganization.Setting != null
                    ? new OrganizationSettingResponse
                    {
                        TaskOverdueThreshold = latestOrganization.Setting.TaskOverdueThreshold,
                        WeeklyReportDeliveryDay = latestOrganization.Setting.WeeklyReportDeliveryDay,
                        MailFromAddress = latestOrganization.Setting.MailFromAddress,
                        MailFromName = latestOrganization.Setting.MailFromName,
                        GenerativeApiVendor = latestOrganization.Setting.GenerativeApiVendor,
                        GenerativeApiKey = latestOrganization.Setting.GenerativeApiKey,
                        GenerativeApiModel = latestOrganization.Setting.GenerativeApiModel,
                        Plan = latestOrganization.Setting.Plan,
                        HelpNotificationTarget = latestOrganization.Setting.HelpNotificationTarget,
                        RequireEstimateOnTaskCreation = latestOrganization.Setting.RequireEstimateOnTaskCreation,
                        EnforcePredecessorCompletion = latestOrganization.Setting.EnforcePredecessorCompletion,
                        DashboardHelpCommentMaxCount = latestOrganization.Setting.DashboardHelpCommentMaxCount,
                        GroupChatScope = latestOrganization.Setting.GroupChatScope,
                        DefaultWorkspaceMode = latestOrganization.Setting.DefaultWorkspaceMode,
                        GamificationEnabled = latestOrganization.Setting.GamificationEnabled,
                        GamificationBadgeVisibility = latestOrganization.Setting.GamificationBadgeVisibility,
                        GamificationAllowUserOverride = latestOrganization.Setting.GamificationAllowUserOverride,
                        BotGroupChatMessagesEnabled = latestOrganization.Setting.BotGroupChatMessagesEnabled,
                        RowVersion = latestOrganization.Setting.RowVersion,
                    }
                    : new OrganizationSettingResponse
                    {
                        TaskOverdueThreshold = 0,
                        WeeklyReportDeliveryDay = 0,
                        GenerativeApiVendor = GenerativeApiVendor.None,
                        GenerativeApiKey = null,
                        GenerativeApiModel = null,
                        Plan = OrganizationPlan.Free,
                        HelpNotificationTarget = null,
                        RequireEstimateOnTaskCreation = false,
                        EnforcePredecessorCompletion = false,
                        DashboardHelpCommentMaxCount = 6,
                        GroupChatScope = null,
                        DefaultWorkspaceMode = null,
                        GamificationEnabled = true,
                        GamificationBadgeVisibility = BadgeVisibility.Private,
                        GamificationAllowUserOverride = true,
                        BotGroupChatMessagesEnabled = true,
                        RowVersion = 0,
                    },
            }
        );
    }

    /// <summary>
    /// 組織の公開設定を取得（センシティブ情報を除外）
    /// </summary>
    /// <param name="organizationId">組織ID</param>
    /// <returns>組織の公開設定</returns>
    public async Task<OrganizationPublicSettings> GetOrganizationPublicSettingsAsync(int organizationId)
    {
        var setting = await _context.OrganizationSettings
            .AsNoTracking()
            .FirstOrDefaultAsync(s => s.OrganizationId == organizationId);

        if (setting == null)
        {
            // 設定が存在しない場合はデフォルト値を返す
            return new OrganizationPublicSettings
            {
                AiProvider = GenerativeApiVendor.None,
                IsAiConfigured = false,
                Plan = OrganizationPlan.Free,
                RequireEstimateOnTaskCreation = false,
                EnforcePredecessorCompletion = false,
                GroupChatScope = null,
                DefaultWorkspaceMode = null,
                GamificationEnabled = true,
                GamificationBadgeVisibility = BadgeVisibility.Private,
                GamificationAllowUserOverride = true,
                BotGroupChatMessagesEnabled = true,
            };
        }

        return new OrganizationPublicSettings
        {
            AiProvider = setting.GenerativeApiVendor,
            IsAiConfigured = setting.GenerativeApiVendor != GenerativeApiVendor.None
                && !string.IsNullOrWhiteSpace(setting.GenerativeApiKey),
            Plan = setting.Plan,
            RequireEstimateOnTaskCreation = setting.RequireEstimateOnTaskCreation,
            EnforcePredecessorCompletion = setting.EnforcePredecessorCompletion,
            GroupChatScope = setting.GroupChatScope,
            DefaultWorkspaceMode = setting.DefaultWorkspaceMode,
            GamificationEnabled = setting.GamificationEnabled,
            GamificationBadgeVisibility = setting.GamificationBadgeVisibility,
            GamificationAllowUserOverride = setting.GamificationAllowUserOverride,
            BotGroupChatMessagesEnabled = setting.BotGroupChatMessagesEnabled,
        };
    }
}