using Pecus.Libs.DB.Models.Enums;
using System.Security.Cryptography;
using System.Text;

namespace Pecus.Libs;

/// <summary>
/// ユーザーのアイデンティティアイコンを取得するヘルパー
/// </summary>
public static class IdentityIconHelper
{
    /// <summary>
    /// GravatarのURLを生成
    /// </summary>
    /// <param name="email">メールアドレス</param>
    /// <param name="size">画像サイズ（ピクセル）</param>
    /// <returns>GravatarのURL</returns>
    public static string GetGravatarUrl(string email, int size = 64)
    {
        if (string.IsNullOrWhiteSpace(email))
        {
            return string.Empty;
        }

        // メールアドレスを小文字に変換してMD5ハッシュを生成
        var emailHash = GetMd5Hash(email.Trim().ToLowerInvariant());

        return $"https://www.gravatar.com/avatar/{emailHash}?s={size}";
    }

    /// <summary>
    /// ユーザーアップロードアイコンのAPI URLを取得
    /// </summary>
    /// <remarks>
    /// <para>
    /// avatarPath は以下の形式に対応しています：
    /// </para>
    /// <list type="bullet">
    /// <item><description>ファイル名のみ: "filename.webp"</description></item>
    /// <item><description>API パス: "/api/downloads/avatar/3/filename.webp"</description></item>
    /// <item><description>相対パス: "avatar/3/filename.webp"</description></item>
    /// </list>
    /// <para>
    /// いずれの形式でも、API URL形式（/api/downloads/avatar/{userId}/{fileName}）を返します。
    /// フロントエンドはこのURLをプロキシ経由でアクセスします。
    /// </para>
    /// </remarks>
    /// <param name="userId">ユーザーID</param>
    /// <param name="avatarPath">アバターパス（ファイル名 or API パス or 相対パス）</param>
    /// <returns>API URL形式のアイコンURL（例: "/api/downloads/avatar/3/filename.webp"）、失敗時は空文字列</returns>
    public static string GetUserAvatarUrl(int userId, string? avatarPath)
    {
        // 入力検証
        if (string.IsNullOrWhiteSpace(avatarPath))
        {
            return string.Empty;
        }

        // avatarPath が既に API パス形式の場合はそのまま返す
        if (avatarPath.StartsWith("/api/downloads/", StringComparison.OrdinalIgnoreCase))
        {
            return avatarPath;
        }

        // ファイル名を抽出
        var fileName = ExtractFileName(avatarPath);

        // API URL形式で返却
        return $"/api/downloads/avatar/{userId}/{fileName}";
    }

    /// <summary>
    /// パス文字列からファイル名を抽出
    /// </summary>
    /// <param name="path">ファイルパスまたはファイル名</param>
    /// <returns>ファイル名部分</returns>
    private static string ExtractFileName(string path)
    {
        // パス区切り文字が含まれている場合はファイル名のみを抽出
        // 例: "/api/downloads/avatar/3/file.png" → "file.png"
        //     "file.png" → "file.png"
        return path.Contains('/') || path.Contains('\\')
            ? Path.GetFileName(path)
            : path;
    }

    /// <summary>
    /// 自動生成されたアイデンティティアイコンのURLを取得
    /// </summary>
    /// <param name="userId">ユーザーID</param>
    /// <param name="username">ユーザー名</param>
    /// <param name="size">画像サイズ（ピクセル）</param>
    /// <returns>自動生成アイコンのURL</returns>
    public static string GetAutoGeneratedIconUrl(int userId, string username, int size = 200)
    {
        // UI Avatarsを使用
        var encodedName = Uri.EscapeDataString(username);
        return $"https://ui-avatars.com/api/?name={encodedName}&size={size}&rounded=true";
    }

    /// <summary>
    /// ユーザーのアイデンティティアイコンURLを取得
    /// </summary>
    /// <param name="iconType">アイコンタイプ</param>
    /// <param name="userId">ユーザーID</param>
    /// <param name="username">ユーザー名</param>
    /// <param name="email">メールアドレス</param>
    /// <param name="avatarPath">アバターパス（UserAvatarの場合）</param>
    /// <param name="size">画像サイズ</param>
    /// <returns>アイコンのURL（必ず有効な文字列を返す）</returns>
    public static string GetIdentityIconUrl(
        AvatarType? iconType,
        int userId,
        string username,
        string email,
        string? avatarPath = null,
        int size = 200
    )
    {
        return iconType switch
        {
            AvatarType.Gravatar => GetGravatarUrl(email, size),
            AvatarType.UserAvatar => GetUserAvatarUrlOrFallback(
                userId: userId,
                username: username,
                avatarPath: avatarPath,
                size: size
            ),
            AvatarType.AutoGenerated => GetAutoGeneratedIconUrl(userId, username, size),
            _ => GetAutoGeneratedIconUrl(userId, username, size), // デフォルトは自動生成
        };
    }

    /// <summary>
    /// UserAvatar取得を試み、失敗時はAutoGeneratedにフォールバック
    /// </summary>
    private static string GetUserAvatarUrlOrFallback(
        int userId,
        string username,
        string? avatarPath,
        int size
    )
    {
        var userAvatarUrl = GetUserAvatarUrl(
            userId: userId,
            avatarPath: avatarPath
        );

        // UserAvatarが取得できなかった場合（空文字列）はAutoGeneratedにフォールバック
        return string.IsNullOrEmpty(userAvatarUrl)
            ? GetAutoGeneratedIconUrl(userId, username, size)
            : userAvatarUrl;
    }

    /// <summary>
    /// MD5ハッシュを生成
    /// </summary>
    private static string GetMd5Hash(string input)
    {
        using var md5 = MD5.Create();
        var inputBytes = Encoding.UTF8.GetBytes(input);
        var hashBytes = md5.ComputeHash(inputBytes);

        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }

    /// <summary>
    /// デフォルトのアイコンタイプを取得
    /// </summary>
    /// <returns>デフォルトのアイコンタイプ</returns>
    public static string GetDefaultIconType() => "auto-generated";
}