using Pecus.Libs.DB.Models.Enums;
using System.Security.Cryptography;
using System.Text;

namespace Pecus.Libs;

/// <summary>
/// ユーザーのアイデンティティアイコンを取得するヘルパー
/// </summary>
public static class IdentityIconHelper
{
    /// <summary>
    /// アイデンティティアイコンのタイプ
    /// </summary>
    public enum IconType
    {
        /// <summary>
        /// Gravatarを使用
        /// </summary>
        Gravatar,

        /// <summary>
        /// ユーザーがアップロードしたアイコン
        /// </summary>
        UserAvatar,

        /// <summary>
        /// 自動生成されたアイデンティティアイコン
        /// </summary>
        AutoGenerated,
    }

    /// <summary>
    /// GravatarのURLを生成
    /// </summary>
    /// <param name="email">メールアドレス</param>
    /// <param name="size">画像サイズ（ピクセル）</param>
    /// /// <returns>GravatarのURL</returns>
    public static string GetGravatarUrl(string email, int size = 64)
    {
        if (string.IsNullOrWhiteSpace(email))
        {
            return string.Empty;
        }

        // メールアドレスを小文字に変換してMD5ハッシュを生成
        var emailHash = GetMd5Hash(email.Trim().ToLowerInvariant());

        return $"https://www.gravatar.com/avatar/{emailHash}?s={size}";
    }

    /// <summary>
    /// ユーザーアップロードアイコンのURLを取得（Base64 DataURL形式）
    /// </summary>
    /// <param name="organizationId">組織ID</param>
    /// <param name="userId">ユーザーID</param>
    /// <param name="avatarPath">アバターの仮想パス（ファイル名）</param>
    /// <param name="uploadsPath">アップロードファイルのルートパス（デフォルト: "uploads"）</param>
    /// <returns>Base64 DataURL形式のアイコンURL、失敗時は空文字列</returns>
    public static string GetUserAvatarUrl(
        int? organizationId,
        int userId,
        string? avatarPath,
        string uploadsPath = "uploads"
    )
    {
        if (string.IsNullOrWhiteSpace(avatarPath) || !organizationId.HasValue)
        {
            return string.Empty;
        }

        try
        {
            // ファイルパスを構築（FileDownloadControllerと同じロジック）
            var filePath = Path.Combine(
                uploadsPath,
                organizationId.Value.ToString(),
                "avatar",
                userId.ToString(),
                avatarPath
            );

            if (!File.Exists(filePath))
            {
                return string.Empty;
            }

            // ファイルを読み込んでBase64変換
            var fileBytes = File.ReadAllBytes(filePath);
            var base64 = Convert.ToBase64String(fileBytes);

            // Content-Typeを推測（拡張子から）
            var extension = Path.GetExtension(avatarPath).ToLowerInvariant();
            var mimeType = extension switch
            {
                ".png" => "image/png",
                ".jpg" or ".jpeg" => "image/jpeg",
                ".gif" => "image/gif",
                ".webp" => "image/webp",
                _ => "image/jpeg"
            };

            return $"data:{mimeType};base64,{base64}";
        }
        catch
        {
            // ファイル読み込み失敗時は空文字列を返す
            return string.Empty;
        }
    }

    /// <summary>
    /// 自動生成されたアイデンティティアイコンのURLを取得
    /// </summary>
    /// <param name="userId">ユーザーID</param>
    /// <param name="username">ユーザー名</param>
    /// <param name="size">画像サイズ（ピクセル）</param>
    /// <returns>自動生成アイコンのURL</returns>
    public static string GetAutoGeneratedIconUrl(int userId, string username, int size = 200)
    {
        // TODO: 実際の自動生成アイコンサービスに応じて実装を調整
        // オプション:
        // 1. DiceBear API: https://dicebear.com/
        // 2. UI Avatars: https://ui-avatars.com/
        // 3. BoringAvatars: https://boringavatars.com/
        // 4. 独自実装のアイコン生成サービス

        // スタブ実装: UI Avatarsを使用
        var encodedName = Uri.EscapeDataString(username);
        return $"https://ui-avatars.com/api/?name={encodedName}&size={size}&rounded=true";
    }

    /// <summary>
    /// ユーザーのアイデンティティアイコンURLを取得
    /// </summary>
    /// <param name="iconType">アイコンタイプ</param>
    /// <param name="organizationId">組織ID（UserAvatarの場合必須）</param>
    /// <param name="userId">ユーザーID</param>
    /// <param name="username">ユーザー名</param>
    /// <param name="email">メールアドレス</param>
    /// <param name="avatarPath">アバターパス（UserAvatarの場合）</param>
    /// <param name="uploadsPath">アップロードファイルのルートパス（デフォルト: "uploads"）</param>
    /// <param name="size">画像サイズ</param>
    /// <returns>アイコンのURL</returns>
    public static string GetIdentityIconUrl(
        AvatarType? iconType,
        int? organizationId,
        int userId,
        string username,
        string email,
        string? avatarPath = null,
        string uploadsPath = "uploads",
        int size = 200
    ) =>
        iconType switch
        {
            AvatarType.Gravatar => GetGravatarUrl(email, size),
            AvatarType.UserAvatar => GetUserAvatarUrl(
                organizationId: organizationId,
                userId: userId,
                avatarPath: avatarPath,
                uploadsPath: uploadsPath
            ),
            AvatarType.AutoGenerated => GetAutoGeneratedIconUrl(userId, username, size),
            _ => GetAutoGeneratedIconUrl(userId, username, size), // デフォルトは自動生成
        };

    /// <summary>
    /// MD5ハッシュを生成
    /// </summary>
    private static string GetMd5Hash(string input)
    {
        using var md5 = MD5.Create();
        var inputBytes = Encoding.UTF8.GetBytes(input);
        var hashBytes = md5.ComputeHash(inputBytes);

        return Convert.ToHexString(hashBytes).ToLowerInvariant();
    }

    /// <summary>
    /// デフォルトのアイコンタイプを取得
    /// </summary>
    /// <returns>デフォルトのアイコンタイプ</returns>
    public static string GetDefaultIconType() => "auto-generated";

}
