/* tslint:disable */
/* eslint-disable */
/**
 * Pecus API
 * AIを社畜扱いして作成するWebAPIです。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOrganizationRequest,
  ErrorResponse,
  OrganizationWithAdminResponse,
} from '../models/index';
import {
    CreateOrganizationRequestFromJSON,
    CreateOrganizationRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    OrganizationWithAdminResponseFromJSON,
    OrganizationWithAdminResponseToJSON,
} from '../models/index';

export interface ApiEntranceOrganizationsPostRequest {
    createOrganizationRequest?: CreateOrganizationRequest;
}

/**
 * 
 */
export class EntranceOrganizationApi extends runtime.BaseAPI {

    /**
     * 新規組織を登録し、管理者ユーザーを同時に作成します。  このエンドポイントは未認証でアクセス可能です（新規サインアップ用）。
     * 組織登録（管理者ユーザーも同時作成）
     */
    async apiEntranceOrganizationsPostRaw(requestParameters: ApiEntranceOrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrganizationWithAdminResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/entrance/organizations`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrganizationRequestToJSON(requestParameters['createOrganizationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationWithAdminResponseFromJSON(jsonValue));
    }

    /**
     * 新規組織を登録し、管理者ユーザーを同時に作成します。  このエンドポイントは未認証でアクセス可能です（新規サインアップ用）。
     * 組織登録（管理者ユーザーも同時作成）
     */
    async apiEntranceOrganizationsPost(requestParameters: ApiEntranceOrganizationsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrganizationWithAdminResponse> {
        const response = await this.apiEntranceOrganizationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
