import { z } from 'zod';

/**
 * ユーザー名（最大50文字）
 */
export const usernameSchema = z
  .string()
  .min(1, 'ユーザー名は必須です。')
  .max(50, 'ユーザー名は50文字以内で入力してください。');

/**
 * メールアドレス（OpenAPI より最大100文字）
 */
export const newEmailSchema = z
  .email('有効なメールアドレスを入力してください。')
  .max(100, 'メールアドレスは100文字以内で入力してください。');

/**
 * 現在のパスワード
 */
export const currentPasswordSchema = z.string().min(1, '現在のパスワードは必須です。');

/**
 * 新しいパスワード（WebAPI要件: 大小文字・数字必須）
 * 要件: 最小8文字、大文字・小文字・数字を必ず含む
 */
export const newPasswordSchema = z
  .string()
  .min(8, 'パスワードは8文字以上で入力してください。')
  .max(100, 'パスワードは100文字以内で入力してください。')
  .regex(/[a-z]/, '小文字を含める必要があります。')
  .regex(/[A-Z]/, '大文字を含める必要があります。')
  .regex(/\d/, '数字を含める必要があります。');

/**
 * 確認用パスワード
 */
export const confirmPasswordSchema = newPasswordSchema;

/**
 * アバター種別
 */
export const avatarTypeSchema = z.enum(['Gravatar', 'UserAvatar', 'AutoGenerated'], {
  error: 'アバター種別が不正です。',
});

/**
 * スキル ID リスト
 */
export const skillIdsSchema = z.array(z.number().int().positive()).optional().nullable();

// ============================================
// フォーム別スキーマ
// ============================================

/**
 * メール変更フォーム（トークンベース認証）
 */
export const updateEmailFormSchema = z.object({
  newEmail: newEmailSchema,
  currentPassword: currentPasswordSchema,
});
export type UpdateEmailFormInput = z.infer<typeof updateEmailFormSchema>;

/**
 * パスワード変更フォーム
 */
export const updatePasswordFormSchema = z
  .object({
    currentPassword: currentPasswordSchema,
    newPassword: newPasswordSchema,
    confirmPassword: confirmPasswordSchema,
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    error: '新しいパスワードが一致しません。',
    path: ['confirmPassword'],
  })
  .refine((data) => data.currentPassword !== data.newPassword, {
    error: '新しいパスワードは現在のパスワードと異なる必要があります。',
    path: ['newPassword'],
  });
export type UpdatePasswordFormInput = z.infer<typeof updatePasswordFormSchema>;

/**
 * プロフィール更新フォーム（ユーザー名、アバター）
 */
export const updateProfileFormSchema = z.object({
  username: usernameSchema.optional(),
  avatarType: avatarTypeSchema.optional(),
});
export type UpdateProfileFormInput = z.infer<typeof updateProfileFormSchema>;

/**
 * スキル設定フォーム
 */
export const updateSkillsFormSchema = z.object({
  skillIds: skillIdsSchema,
});
export type UpdateSkillsFormInput = z.infer<typeof updateSkillsFormSchema>;

/**
 * ユーザー作成フォーム（管理者用・パスワードなし）
 * Note: roles は配列のためフォームバリデーションでは扱わず、コンポーネント側で別途バリデーションする
 */
export const createUserWithoutPasswordSchema = z.object({
  username: usernameSchema,
  email: newEmailSchema,
});
export type CreateUserWithoutPasswordInput = z.infer<typeof createUserWithoutPasswordSchema>;

/**
 * スキル名（最大100文字）
 */
export const skillNameSchema = z
  .string()
  .min(1, 'スキル名は必須です。')
  .max(100, 'スキル名は100文字以内で入力してください。');

/**
 * スキル説明（最大500文字、オプション）
 */
export const skillDescriptionSchema = z
  .string()
  .max(500, '説明は500文字以内で入力してください。')
  .optional()
  .or(z.literal(''));

/**
 * スキル作成フォーム（管理者用）
 */
export const createSkillSchema = z.object({
  name: skillNameSchema,
  description: skillDescriptionSchema,
});
export type CreateSkillInput = z.infer<typeof createSkillSchema>;

/**
 * タグ名（最大50文字）
 */
export const tagNameSchema = z.string().min(1, 'タグ名は必須です。').max(50, 'タグ名は50文字以内で入力してください。');

/**
 * タグ作成フォーム（管理者用）
 */
export const createTagSchema = z.object({
  name: tagNameSchema,
});
export type CreateTagInput = z.infer<typeof createTagSchema>;

// ============================================
// Server Action 入力スキーマ
// ============================================

const avatarTypeNullableSchema = z
  .enum(['Gravatar', 'UserAvatar', 'AutoGenerated'], {
    error: 'アバター種別が不正です。',
  })
  .nullable()
  .optional();

const landingPageSchema = z
  .enum(['Dashboard', 'Workspace', 'MyItems', 'Tasks', 'Committer'], {
    error: 'ログイン後のページを選択してください。',
  })
  .nullable()
  .optional();

const focusScorePrioritySchema = z
  .enum(['Priority', 'Deadline', 'SuccessorImpact'], {
    error: 'スコアリング優先要素を選択してください。',
  })
  .nullable()
  .optional();

const badgeVisibilitySchema = z
  .enum(['Private', 'Workspace', 'Organization'], {
    error: 'バッジの公開範囲を選択してください。',
  })
  .optional();

export const updateProfileActionInputSchema = z.object({
  username: usernameSchema.optional(),
  avatarType: avatarTypeNullableSchema,
  userAvatarPath: z.string().optional(),
  skillIds: z.array(z.number().int().positive()).optional(),
  rowVersion: z
    .number({ error: '行バージョンが不正です。' })
    .int('行バージョンが不正です。')
    .nonnegative('行バージョンが不正です。'),
});

export type UpdateProfileActionInput = z.infer<typeof updateProfileActionInputSchema>;

export const verifyEmailChangeInputSchema = z.object({
  token: z.string({ error: 'トークンが不正です。' }).min(1, 'トークンが不正です。'),
});

export type VerifyEmailChangeInput = z.infer<typeof verifyEmailChangeInputSchema>;

export const deleteDeviceInputSchema = z.object({
  deviceId: z.number({ error: '端末IDが不正です。' }).int('端末IDが不正です。').positive('端末IDが不正です。'),
});

export type DeleteDeviceInput = z.infer<typeof deleteDeviceInputSchema>;

export const logoutOtherDevicesInputSchema = z.object({});

export type LogoutOtherDevicesInput = z.infer<typeof logoutOtherDevicesInputSchema>;

export const uploadAvatarFileInputSchema = z.object({
  fileName: z.string({ error: 'ファイル名が不正です。' }).min(1, 'ファイル名が不正です。'),
  fileType: z.string({ error: 'ファイルタイプが不正です。' }).min(1, 'ファイルタイプが不正です。'),
  arrayBuffer: z.custom<ArrayBuffer>((value) => value instanceof ArrayBuffer, {
    error: 'ファイルデータが不正です。',
  }),
});

export type UploadAvatarFileInput = z.infer<typeof uploadAvatarFileInputSchema>;

export const deleteAvatarFileInputSchema = z.object({
  fileName: z.string({ error: 'ファイル名が不正です。' }).min(1, 'ファイル名が不正です。'),
  resourceId: z
    .number({ error: 'リソースIDが不正です。' })
    .int('リソースIDが不正です。')
    .positive('リソースIDが不正です。'),
});

export type DeleteAvatarFileInput = z.infer<typeof deleteAvatarFileInputSchema>;

export const updateUserSettingInputSchema = z.object({
  canReceiveEmail: z.boolean({ error: 'メール通知設定が不正です。' }),
  canReceiveRealtimeNotification: z.boolean({ error: 'リアルタイム通知設定が不正です。' }),
  timeZone: z.string({ error: 'タイムゾーンが不正です。' }).min(1, 'タイムゾーンが不正です。'),
  language: z.string({ error: '言語設定が不正です。' }).min(1, '言語設定が不正です。'),
  landingPage: landingPageSchema,
  focusScorePriority: focusScorePrioritySchema,
  focusTasksLimit: z
    .number({ error: 'やることピックアップ件数が不正です。' })
    .int('やることピックアップ件数が不正です。')
    .min(5, 'やることピックアップ件数が不正です。')
    .max(20, 'やることピックアップ件数が不正です。'),
  waitingTasksLimit: z
    .number({ error: '待機中タスク件数が不正です。' })
    .int('待機中タスク件数が不正です。')
    .min(5, '待機中タスク件数が不正です。')
    .max(20, '待機中タスク件数が不正です。'),
  badgeVisibility: badgeVisibilitySchema,
  rowVersion: z
    .number({ error: '行バージョンが不正です。' })
    .int('行バージョンが不正です。')
    .nonnegative('行バージョンが不正です。'),
});

export type UpdateUserSettingInput = z.infer<typeof updateUserSettingInputSchema>;

export const respondToLandingPageRecommendationInputSchema = z.object({
  action: z.enum(['Accept', 'Reject'], { error: '応答アクションが不正です。' }),
});

export type RespondToLandingPageRecommendationInput = z.infer<typeof respondToLandingPageRecommendationInputSchema>;
