// このファイルは自動生成されます。手動で編集しないでください。
// Generated by: scripts/generate-pecus-api-client.js

import { OpenAPI } from "./pecus/core/OpenAPI";
import {
  AchievementService,
  ActivityService,
  AdminExternalApiKeysService,
  AdminOrganizationService,
  AdminSkillService,
  AdminTagService,
  AdminUserService,
  AdminWorkspaceService,
  AgendaNotificationService,
  AgendaService,
  AiAssistantService,
  BackOfficeMonitoringService,
  BackOfficeNotificationsService,
  BackOfficeOrganizationsService,
  ChatService,
  DashboardService,
  EntranceAuthService,
  EntrancePasswordService,
  ExternalService,
  FileService,
  FocusService,
  MasterService,
  MyService,
  PersonalItemNoteService,
  ProfileService,
  TagService,
  TaskCommentService,
  UserService,
  WorkspaceAttachmentsService,
  WorkspaceItemService,
  WorkspaceService,
  WorkspaceTaskService
} from "./pecus";

/**
 * OpenAPI 設定を初期化する関数
 * @param baseUrl - API のベース URL
 * @param getToken - トークン取得関数（オプション）
 */
export function configureOpenAPI(
  baseUrl: string,
  getToken?: () => Promise<string | undefined>
) {
  OpenAPI.BASE = baseUrl;
  OpenAPI.WITH_CREDENTIALS = true;
  OpenAPI.CREDENTIALS = 'include';
  
  if (getToken) {
    OpenAPI.TOKEN = async () => {
      const token = await getToken();
      return token || '';
    };
  }
}

/**
 * API サービスのインスタンスを返す関数
 * @returns API サービスのオブジェクト
 */
export function createApiClientInstances() {
  return {
    achievement: AchievementService,
    activity: ActivityService,
    adminExternalApiKeys: AdminExternalApiKeysService,
    adminOrganization: AdminOrganizationService,
    adminSkill: AdminSkillService,
    adminTag: AdminTagService,
    adminUser: AdminUserService,
    adminWorkspace: AdminWorkspaceService,
    agendaNotification: AgendaNotificationService,
    agenda: AgendaService,
    aiAssistant: AiAssistantService,
    backOfficeMonitoring: BackOfficeMonitoringService,
    backOfficeNotifications: BackOfficeNotificationsService,
    backOfficeOrganizations: BackOfficeOrganizationsService,
    chat: ChatService,
    dashboard: DashboardService,
    entranceAuth: EntranceAuthService,
    entrancePassword: EntrancePasswordService,
    external: ExternalService,
    file: FileService,
    focus: FocusService,
    master: MasterService,
    my: MyService,
    personalItemNote: PersonalItemNoteService,
    profile: ProfileService,
    tag: TagService,
    taskComment: TaskCommentService,
    user: UserService,
    workspaceAttachments: WorkspaceAttachmentsService,
    workspaceItem: WorkspaceItemService,
    workspace: WorkspaceService,
    workspaceTask: WorkspaceTaskService
  };
}
