// このファイルは自動生成されます。手動で編集しないでください。
// Generated by: scripts/generate-pecus-api-client.js

import { OpenAPI } from "./pecus/core/OpenAPI";
import {
  AdminOrganizationService,
  AdminSkillService,
  AdminTagService,
  AdminUserService,
  AdminWorkspaceService,
  BackendGenreService,
  BackendOrganizationService,
  BackendPermissionService,
  BackendRoleService,
  BackendSpecsService,
  EntranceAuthService,
  EntranceOrganizationService,
  EntrancePasswordService,
  FileService,
  MasterService,
  ProfileDeviceService,
  ProfileEmailService,
  ProfileService,
  TagService,
  TestEmailService,
  WorkspaceItemService,
  WorkspaceItemTempAttachmentService,
  WorkspaceService
} from "./pecus";

/**
 * OpenAPI 設定を初期化する関数
 * @param baseUrl - API のベース URL
 * @param getToken - トークン取得関数（オプション）
 */
export function configureOpenAPI(
  baseUrl: string,
  getToken?: () => Promise<string | undefined>
) {
  OpenAPI.BASE = baseUrl;
  OpenAPI.WITH_CREDENTIALS = true;
  OpenAPI.CREDENTIALS = 'include';
  
  if (getToken) {
    OpenAPI.TOKEN = async () => {
      const token = await getToken();
      return token || '';
    };
  }
}

/**
 * API サービスのインスタンスを返す関数
 * @returns API サービスのオブジェクト
 */
export function createApiClientInstances() {
  return {
    adminOrganization: AdminOrganizationService,
    adminSkill: AdminSkillService,
    adminTag: AdminTagService,
    adminUser: AdminUserService,
    adminWorkspace: AdminWorkspaceService,
    backendGenre: BackendGenreService,
    backendOrganization: BackendOrganizationService,
    backendPermission: BackendPermissionService,
    backendRole: BackendRoleService,
    backendSpecs: BackendSpecsService,
    entranceAuth: EntranceAuthService,
    entranceOrganization: EntranceOrganizationService,
    entrancePassword: EntrancePasswordService,
    file: FileService,
    master: MasterService,
    profileDevice: ProfileDeviceService,
    profileEmail: ProfileEmailService,
    profile: ProfileService,
    tag: TagService,
    testEmail: TestEmailService,
    workspaceItem: WorkspaceItemService,
    workspaceItemTempAttachment: WorkspaceItemTempAttachmentService,
    workspace: WorkspaceService
  };
}
