/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type { EditorThemeClasses } from "lexical";

import "./NotionLikeEditorTheme.css";

const theme: EditorThemeClasses = {
  autocomplete: "NotionLikeEditorTheme__autocomplete",
  blockCursor: "NotionLikeEditorTheme__blockCursor",
  characterLimit: "NotionLikeEditorTheme__characterLimit",
  code: "NotionLikeEditorTheme__code",
  codeHighlight: {
    atrule: "NotionLikeEditorTheme__tokenAttr",
    attr: "NotionLikeEditorTheme__tokenAttr",
    boolean: "NotionLikeEditorTheme__tokenProperty",
    builtin: "NotionLikeEditorTheme__tokenSelector",
    cdata: "NotionLikeEditorTheme__tokenComment",
    char: "NotionLikeEditorTheme__tokenSelector",
    class: "NotionLikeEditorTheme__tokenFunction",
    "class-name": "NotionLikeEditorTheme__tokenFunction",
    comment: "NotionLikeEditorTheme__tokenComment",
    constant: "NotionLikeEditorTheme__tokenProperty",
    deleted: "NotionLikeEditorTheme__tokenDeleted",
    doctype: "NotionLikeEditorTheme__tokenComment",
    entity: "NotionLikeEditorTheme__tokenOperator",
    function: "NotionLikeEditorTheme__tokenFunction",
    important: "NotionLikeEditorTheme__tokenVariable",
    inserted: "NotionLikeEditorTheme__tokenInserted",
    keyword: "NotionLikeEditorTheme__tokenAttr",
    namespace: "NotionLikeEditorTheme__tokenVariable",
    number: "NotionLikeEditorTheme__tokenProperty",
    operator: "NotionLikeEditorTheme__tokenOperator",
    prolog: "NotionLikeEditorTheme__tokenComment",
    property: "NotionLikeEditorTheme__tokenProperty",
    punctuation: "NotionLikeEditorTheme__tokenPunctuation",
    regex: "NotionLikeEditorTheme__tokenVariable",
    selector: "NotionLikeEditorTheme__tokenSelector",
    string: "NotionLikeEditorTheme__tokenSelector",
    symbol: "NotionLikeEditorTheme__tokenProperty",
    tag: "NotionLikeEditorTheme__tokenProperty",
    unchanged: "NotionLikeEditorTheme__tokenUnchanged",
    url: "NotionLikeEditorTheme__tokenOperator",
    variable: "NotionLikeEditorTheme__tokenVariable",
  },
  embedBlock: {
    base: "NotionLikeEditorTheme__embedBlock",
    focus: "NotionLikeEditorTheme__embedBlockFocus",
  },
  hashtag: "NotionLikeEditorTheme__hashtag",
  heading: {
    h1: "NotionLikeEditorTheme__h1",
    h2: "NotionLikeEditorTheme__h2",
    h3: "NotionLikeEditorTheme__h3",
    h4: "NotionLikeEditorTheme__h4",
    h5: "NotionLikeEditorTheme__h5",
    h6: "NotionLikeEditorTheme__h6",
  },
  hr: "NotionLikeEditorTheme__hr",
  hrSelected: "NotionLikeEditorTheme__hrSelected",
  image: "editor-image",
  indent: "NotionLikeEditorTheme__indent",
  layoutContainer: "NotionLikeEditorTheme__layoutContainer",
  layoutItem: "NotionLikeEditorTheme__layoutItem",
  link: "NotionLikeEditorTheme__link",
  list: {
    checklist: "NotionLikeEditorTheme__checklist",
    listitem: "NotionLikeEditorTheme__listItem",
    listitemChecked: "NotionLikeEditorTheme__listItemChecked",
    listitemUnchecked: "NotionLikeEditorTheme__listItemUnchecked",
    nested: {
      listitem: "NotionLikeEditorTheme__nestedListItem",
    },
    olDepth: [
      "NotionLikeEditorTheme__ol1",
      "NotionLikeEditorTheme__ol2",
      "NotionLikeEditorTheme__ol3",
      "NotionLikeEditorTheme__ol4",
      "NotionLikeEditorTheme__ol5",
    ],
    ul: "NotionLikeEditorTheme__ul",
    ol: "NotionLikeEditorTheme__ol",
  },
  mark: "NotionLikeEditorTheme__mark",
  markOverlap: "NotionLikeEditorTheme__markOverlap",
  paragraph: "NotionLikeEditorTheme__paragraph",
  quote: "NotionLikeEditorTheme__quote",
  specialText: "NotionLikeEditorTheme__specialText",
  tab: "NotionLikeEditorTheme__tabNode",
  table: "NotionLikeEditorTheme__table",
  tableAddColumns: "NotionLikeEditorTheme__tableAddColumns",
  tableAddRows: "NotionLikeEditorTheme__tableAddRows",
  tableAlignment: {
    center: "NotionLikeEditorTheme__tableAlignmentCenter",
    right: "NotionLikeEditorTheme__tableAlignmentRight",
  },
  tableCell: "NotionLikeEditorTheme__tableCell",
  tableCellActionButton: "NotionLikeEditorTheme__tableCellActionButton",
  tableCellActionButtonContainer: "NotionLikeEditorTheme__tableCellActionButtonContainer",
  tableCellHeader: "NotionLikeEditorTheme__tableCellHeader",
  tableCellResizer: "NotionLikeEditorTheme__tableCellResizer",
  tableCellSelected: "NotionLikeEditorTheme__tableCellSelected",
  tableFrozenColumn: "NotionLikeEditorTheme__tableFrozenColumn",
  tableFrozenRow: "NotionLikeEditorTheme__tableFrozenRow",
  tableRowStriping: "NotionLikeEditorTheme__tableRowStriping",
  tableScrollableWrapper: "NotionLikeEditorTheme__tableScrollableWrapper",
  tableSelected: "NotionLikeEditorTheme__tableSelected",
  tableSelection: "NotionLikeEditorTheme__tableSelection",
  text: {
    bold: "NotionLikeEditorTheme__textBold",
    capitalize: "NotionLikeEditorTheme__textCapitalize",
    code: "NotionLikeEditorTheme__textCode",
    highlight: "NotionLikeEditorTheme__textHighlight",
    italic: "NotionLikeEditorTheme__textItalic",
    lowercase: "NotionLikeEditorTheme__textLowercase",
    strikethrough: "NotionLikeEditorTheme__textStrikethrough",
    subscript: "NotionLikeEditorTheme__textSubscript",
    superscript: "NotionLikeEditorTheme__textSuperscript",
    underline: "NotionLikeEditorTheme__textUnderline",
    underlineStrikethrough: "NotionLikeEditorTheme__textUnderlineStrikethrough",
    uppercase: "NotionLikeEditorTheme__textUppercase",
  },
};

export default theme;
