import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import AppFooter from '@/components/common/AppFooter.server';
import FlyonuiScript from '@/libs/flyon/FlyonuiScript';

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

// HackGen フォントの設定(localFont を使用)
const hackGen = localFont({
  src: [
    {
      path: '../fonts/HackGen-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/HackGen-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-hackgen',
  display: 'swap',
  fallback: ['Source Han Code JP', 'Noto Sans Mono CJK JP', 'monospace'],
});

export const metadata: Metadata = {
  title: 'Coati',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoSansJP.className} ${hackGen.variable} antialiased`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const storedTheme = localStorage.getItem('theme');
                  if (storedTheme === 'light' || storedTheme === 'dark') {
                    document.documentElement.setAttribute('data-theme', storedTheme);
                  } else {
                    // デフォルトは auto
                    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                    document.documentElement.setAttribute('data-theme', prefersDark ? 'dark' : 'light');
                  }
                } catch (e) {}
              })()
            `,
          }}
        />
        <div className="flex h-screen flex-col">
          <main className="flex-1 overflow-auto">{children}</main>
          <AppFooter />
        </div>
        <FlyonuiScript />
        <script src="/scripts/flyonui.js"></script>
      </body>
    </html>
  );
}
