using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace pecus.DbManager.Migrations
{
    /// <inheritdoc />
    public partial class ChangeAvatarTypeToEnum : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Step 1: まずデフォルト値を削除
            migrationBuilder.Sql(
                @"ALTER TABLE ""Users""
                  ALTER COLUMN ""AvatarType"" DROP DEFAULT");

            // Step 2: PostgreSQL で USING 句を使用して明示的に型変換
            // 既存データを整数値にマッピングしながら型を変更
            migrationBuilder.Sql(
                @"ALTER TABLE ""Users""
                  ALTER COLUMN ""AvatarType"" TYPE integer
                  USING (CASE
                      WHEN ""AvatarType"" = 'Gravatar' THEN 1
                      WHEN ""AvatarType"" = 'UserAvatar' THEN 2
                      WHEN ""AvatarType"" = 'AutoGenerated' THEN 3
                      WHEN ""AvatarType"" = 'auto-generated' THEN 3
                      ELSE 3
                  END)::integer");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Step 1: 数値を文字列に逆変換して元の型に戻す
            migrationBuilder.Sql(
                @"ALTER TABLE ""Users""
                  ALTER COLUMN ""AvatarType"" TYPE character varying(20)
                  USING (CASE
                      WHEN ""AvatarType"" = 1 THEN 'Gravatar'
                      WHEN ""AvatarType"" = 2 THEN 'UserAvatar'
                      WHEN ""AvatarType"" = 3 THEN 'auto-generated'
                      ELSE 'auto-generated'
                  END)::character varying(20)");

            // Step 2: デフォルト値を復元
            migrationBuilder.Sql(
                @"ALTER TABLE ""Users""
                  ALTER COLUMN ""AvatarType"" SET DEFAULT 'auto-generated'");
        }
    }
}
