// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pecus.Libs.DB;
using System;

#nullable disable

namespace pecus.DbManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120060000_ChangeAgendaExceptionToOccurrenceIndex")]
    partial class ChangeAgendaExceptionToOccurrenceIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // AgendaException entity with OccurrenceIndex instead of OriginalStartAt
            modelBuilder.Entity("Pecus.Libs.DB.Models.AgendaException", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgendaId")
                        .HasColumnType("bigint");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedDescription")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedLocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ModifiedStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModifiedUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OccurrenceIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("AgendaId", "OccurrenceIndex")
                        .IsUnique();

                    b.ToTable("AgendaExceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
